use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsStr;
use std::fs::{self, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use super::project::{
    list_areas, load_area, read_config, require_checked_out_area_branch, require_fresh_area_link,
};
use super::{
    CHANGE_ID_TRAILER, CommandOutput, SCHEMA_VERSION, ZdevError, ZdevStateLock, generate_change_id,
    git_operation, git_output, relative, validate_nonempty_line, validate_segment, write_atomic,
};

const GENERATED_MARKER: &str = "<!-- Generated by zdev. Edit task files, not this summary. -->";

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum TaskStatus {
    Open,
    Done,
}

impl TaskStatus {
    fn as_str(self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Done => "done",
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct TaskHeader {
    schema_version: u64,
    id: String,
    key: String,
    area: String,
    status: TaskStatus,
    #[serde(default)]
    blocked_by: Vec<String>,
}

#[derive(Clone, Debug)]
struct Task {
    header: TaskHeader,
    title: String,
    body: String,
    path: PathBuf,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct TaskBundle {
    schema_version: u64,
    area: String,
    tasks: Vec<TaskDraft>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct TaskDraft {
    key: String,
    title: String,
    #[serde(default)]
    blocked_by: Vec<String>,
    outcome: String,
    context: Option<String>,
    #[serde(default)]
    boundaries: Vec<String>,
    done_when: Vec<String>,
    #[serde(default)]
    validation: Vec<String>,
}

#[derive(Serialize)]
struct TaskView<'a> {
    id: &'a str,
    title: &'a str,
    status: &'static str,
    state: &'static str,
    blocked_by: &'a [String],
    path: String,
}

fn read_task_bundle(source: &Path) -> Result<TaskBundle, ZdevError> {
    let bytes = if source == Path::new("-") {
        let mut bytes = Vec::new();
        io::stdin()
            .read_to_end(&mut bytes)
            .map_err(|error| ZdevError::io("Cannot read task bundle from standard input", error))?;
        bytes
    } else {
        fs::read(source)
            .map_err(|error| ZdevError::io(format!("Cannot read {}", source.display()), error))?
    };
    serde_json::from_slice(&bytes)
        .map_err(|error| ZdevError::new(format!("Invalid task bundle: {error}")))
}

fn validate_task_bundle(bundle: &TaskBundle, area: &str) -> Result<(), ZdevError> {
    if bundle.schema_version != SCHEMA_VERSION || bundle.area != area {
        return Err(ZdevError::new(
            "Task bundle does not match the selected area",
        ));
    }
    if bundle.tasks.is_empty() {
        return Err(ZdevError::new("Task bundle contains no tasks"));
    }
    let mut seen_keys = BTreeSet::new();
    for task in &bundle.tasks {
        validate_segment(&task.key, "Task key")?;
        validate_nonempty_line(&task.title, "Task title")?;
        validate_nonempty_line(&task.outcome, "Task outcome")?;
        if task
            .context
            .as_deref()
            .is_some_and(|context| context.trim().is_empty())
        {
            return Err(ZdevError::new(format!(
                "Task {} has empty context",
                task.key
            )));
        }
        if task.done_when.is_empty() {
            return Err(ZdevError::new(format!(
                "Task {} has no done conditions",
                task.key
            )));
        }
        if !seen_keys.insert(task.key.as_str()) {
            return Err(ZdevError::new(format!("Duplicate task key: {}", task.key)));
        }
    }
    Ok(())
}

fn task_bundle_approval_id(bundle: &TaskBundle) -> Result<String, ZdevError> {
    let canonical = serde_json::to_vec(bundle)
        .map_err(|error| ZdevError::new(format!("Cannot fingerprint task bundle: {error}")))?;
    let hash = canonical.iter().fold(0xcbf29ce484222325_u64, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)
    });
    Ok(format!("T{hash:016x}"))
}

fn approval_value(value: Option<&str>) -> &str {
    value.filter(|value| !value.is_empty()).unwrap_or("None")
}

fn approval_list(values: &[String]) -> String {
    if values.is_empty() {
        "None".to_owned()
    } else {
        values
            .iter()
            .enumerate()
            .map(|(index, value)| format!("{}. {value}", index + 1))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

fn longest_backtick_run(value: &str) -> usize {
    value
        .split(|character| character != '`')
        .map(str::len)
        .max()
        .unwrap_or(0)
}

fn render_task_bundle_approval(bundle: &TaskBundle) -> String {
    let mut document = format!(
        "# Task Bundle\n\n## Area\n{}\n\n## Schema version\n{}",
        bundle.area, bundle.schema_version
    );
    for (index, task) in bundle.tasks.iter().enumerate() {
        document.push_str(&format!(
            "\n\n## Task {}\n\n### Key\n{}\n\n### Title\n{}\n\n### Outcome\n{}\n\n### Context\n{}\n\n### Boundaries\n{}\n\n### Blocked by\n{}\n\n### Done when / proof\n{}\n\n### Validation / Testing\n{}",
            index + 1,
            task.key,
            task.title,
            task.outcome,
            approval_value(task.context.as_deref()),
            approval_list(&task.boundaries),
            approval_list(&task.blocked_by),
            approval_list(&task.done_when),
            approval_list(&task.validation),
        ));
    }
    let fence = "`".repeat(longest_backtick_run(&document).saturating_add(1).max(3));
    format!("{fence}markdown\n{document}\n{fence}")
}

pub(super) fn review(root: &Path, area: &str, source: &Path) -> Result<CommandOutput, ZdevError> {
    load_area(root, area)?;
    let bundle = read_task_bundle(source)?;
    validate_task_bundle(&bundle, area)?;
    let approval = task_bundle_approval_id(&bundle)?;
    let markdown = render_task_bundle_approval(&bundle);
    Ok(CommandOutput::new(
        format!("{markdown}\n\nApproval ID: {approval}"),
        json!({
            "schema_version": SCHEMA_VERSION,
            "status": "reviewed",
            "area": area,
            "approval": approval,
            "markdown": markdown,
        }),
    ))
}

pub(super) fn import(
    root: &Path,
    area: &str,
    source: &Path,
    commit_changes: bool,
    approval: Option<&str>,
) -> Result<CommandOutput, ZdevError> {
    let bundle = read_task_bundle(source)?;
    validate_task_bundle(&bundle, area)?;
    if let Some(approval) = approval {
        let actual = task_bundle_approval_id(&bundle)?;
        if approval != actual {
            return Err(ZdevError::new(format!(
                "Task bundle differs from approved review {approval}; review this bundle and use its approval ID"
            )));
        }
    }
    let _lock = ZdevStateLock::acquire(root)?;
    let (metadata, area_dir) = load_area(root, area)?;
    if commit_changes {
        require_checked_out_area_branch(root, &metadata)?;
        require_committable_task_import(root, area)?;
    }
    let existing = load_tasks(root, area)?;
    let existing_ids = existing
        .iter()
        .map(|task| task.header.id.as_str())
        .collect::<BTreeSet<_>>();
    let existing_keys = existing
        .iter()
        .map(|task| task.header.key.as_str())
        .collect::<BTreeSet<_>>();
    for task in &bundle.tasks {
        if existing_keys.contains(task.key.as_str()) {
            return Err(ZdevError::new(format!("Duplicate task key: {}", task.key)));
        }
    }
    let mut next_number = existing
        .iter()
        .filter_map(|task| task.header.id.rsplit_once('-')?.1.parse::<u64>().ok())
        .max()
        .unwrap_or(0);
    let mut allocated = BTreeMap::new();
    for task in &bundle.tasks {
        next_number += 1;
        allocated.insert(task.key.as_str(), format!("{area}-{next_number:03}"));
    }
    let mut writes = Vec::new();
    for draft in &bundle.tasks {
        let id = allocated[&draft.key.as_str()].clone();
        let blockers = draft
            .blocked_by
            .iter()
            .map(|blocker| {
                if let Some(id) = allocated.get(blocker.as_str()) {
                    Ok((*id).clone())
                } else if existing_ids.contains(blocker.as_str()) {
                    Ok(blocker.clone())
                } else {
                    Err(ZdevError::new(format!(
                        "Task {} has unknown blocker {blocker}",
                        draft.key
                    )))
                }
            })
            .collect::<Result<Vec<_>, _>>()?;
        if blockers.iter().any(|blocker| blocker == &id) {
            return Err(ZdevError::new(format!("Task {} blocks itself", draft.key)));
        }
        let header = TaskHeader {
            schema_version: SCHEMA_VERSION,
            id: id.clone(),
            key: draft.key.clone(),
            area: area.to_owned(),
            status: TaskStatus::Open,
            blocked_by: blockers,
        };
        let path = area_dir.join("tasks").join(format!(
            "{next:03}-{}.md",
            slug(&draft.title),
            next = parse_number(&id)?
        ));
        let body = render_draft(&header, draft)?;
        writes.push((path, body));
    }
    let mut hypothetical = existing.clone();
    for (path, content) in &writes {
        hypothetical.push(parse_task(content, path, area)?);
    }
    validate_graph(&hypothetical)?;
    let index_path = area_dir.join("TASKS.md");
    let previous_index = fs::read(&index_path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", index_path.display()), error))?;
    let mut created = Vec::new();
    for (path, content) in &writes {
        match OpenOptions::new().create_new(true).write(true).open(path) {
            Ok(mut file) => {
                created.push(path.clone());
                if let Err(error) = file
                    .write_all(content.as_bytes())
                    .and_then(|()| file.sync_all())
                {
                    let write_error =
                        ZdevError::io(format!("Cannot write {}", path.display()), error);
                    drop(file);
                    return Err(import_rollback_error(write_error, &created, None));
                }
            }
            Err(error) => {
                let create_error =
                    ZdevError::io(format!("Cannot create {}", path.display()), error);
                return Err(import_rollback_error(create_error, &created, None));
            }
        }
    }
    if let Err(error) = write_index(root, area) {
        return Err(import_rollback_error(
            error,
            &created,
            commit_changes.then_some((index_path.as_path(), previous_index.as_slice())),
        ));
    }
    let ids = writes
        .iter()
        .map(|(_, content)| {
            parse_task(content, Path::new("task.md"), area).map(|task| task.header.id)
        })
        .collect::<Result<Vec<_>, _>>()?;
    if commit_changes {
        let paths = writes
            .iter()
            .map(|(path, _)| path.clone())
            .chain(std::iter::once(index_path.clone()))
            .collect::<Vec<_>>();
        return match commit_task_import(root, area, &paths) {
            Ok((revision, change_id)) => Ok(CommandOutput::new(
                format!(
                    "Added and committed {} tasks to {area} ({revision})",
                    ids.len()
                ),
                json!({"schema_version": SCHEMA_VERSION, "status": "committed", "area": area, "tasks": ids, "commit": revision, "change_id": change_id, "paths": relative_paths(root, &paths)?}),
            )),
            Err(error) => Err(import_rollback_error(
                rollback_task_import_index(root, &paths, error),
                &created,
                Some((index_path.as_path(), previous_index.as_slice())),
            )),
        };
    }
    Ok(CommandOutput::new(
        format!("Added {} tasks to {area}", ids.len()),
        json!({"schema_version": SCHEMA_VERSION, "status": "created", "area": area, "tasks": ids}),
    ))
}

fn import_rollback_error(
    error: ZdevError,
    created: &[PathBuf],
    restore_index: Option<(&Path, &[u8])>,
) -> ZdevError {
    let mut cleanup_errors = created
        .iter()
        .filter_map(|path| {
            fs::remove_file(path)
                .err()
                .map(|cleanup| format!("cannot remove {}: {cleanup}", path.display()))
        })
        .collect::<Vec<_>>();
    if let Some((path, contents)) = restore_index
        && let Err(restore) = write_atomic(path, contents)
    {
        cleanup_errors.push(format!("cannot restore {}: {restore}", path.display()));
    }
    if cleanup_errors.is_empty() {
        ZdevError::new(format!(
            "Could not add tasks; the import was rolled back and no imported task changes were kept. {error}"
        ))
    } else {
        ZdevError::new(format!(
            "Could not add tasks, and cleanup was incomplete. {error}. Resolve these paths before retrying: {}",
            cleanup_errors.join("; "),
        ))
    }
}

fn require_committable_task_import(root: &Path, area: &str) -> Result<(), ZdevError> {
    if let Some(operation) = git_operation(root)? {
        return Err(ZdevError::new(format!(
            "Cannot add and commit tasks while a {operation} is in progress. Finish or abort it, then retry"
        )));
    }
    git_output(root, &["rev-parse", "--verify", "HEAD"]).map_err(|_| {
        ZdevError::new(
            "Cannot add and commit tasks before the repository has a commit. Create the initial commit, then retry",
        )
    })?;
    let area_path = format!(".zdev/{area}");
    let changed = git_output(
        root,
        &[
            "status",
            "--porcelain=v1",
            "--untracked-files=all",
            "--",
            &area_path,
        ],
    )?;
    let ignored = git_output(
        root,
        &[
            "ls-files",
            "--others",
            "--ignored",
            "--exclude-standard",
            "--",
            &area_path,
        ],
    )?;
    if !changed.is_empty() || !ignored.is_empty() {
        return Err(ZdevError::new(format!(
            "Cannot add and commit tasks: {area_path} already has local changes. Commit or resolve them first"
        )));
    }
    Ok(())
}

fn relative_paths(root: &Path, paths: &[PathBuf]) -> Result<Vec<String>, ZdevError> {
    paths
        .iter()
        .map(|path| {
            path.strip_prefix(root)
                .map(|path| path.to_string_lossy().replace('\\', "/"))
                .map_err(|_| {
                    ZdevError::new(format!("Path is outside repository: {}", path.display()))
                })
        })
        .collect()
}

fn commit_task_import(
    root: &Path,
    area: &str,
    paths: &[PathBuf],
) -> Result<(String, String), ZdevError> {
    let relative = relative_paths(root, paths)?;
    let mut add = ProcessCommand::new("git");
    add.args(["add", "-f", "--"]);
    add.args(&relative);
    let output = add
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
        .map_err(|error| ZdevError::io("Cannot stage imported task paths", error))?;
    if !output.status.success() {
        return Err(ZdevError::new(format!(
            "Could not stage the new task files. Resolve the Git error, then retry: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }

    let change_id = generate_change_id()?;
    let mut command = ProcessCommand::new("git");
    command
        .args(["commit", "--only", "-m"])
        .arg(format!("Add tasks to {area}"))
        .args(["-m", &format!("{CHANGE_ID_TRAILER}: {change_id}"), "--"])
        .args(&relative);
    let output = command
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
        .map_err(|error| ZdevError::io("Cannot commit imported task paths", error))?;
    if !output.status.success() {
        return Err(ZdevError::new(format!(
            "Could not commit the new task files. Resolve the Git error, then retry: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    Ok((git_output(root, &["rev-parse", "HEAD"])?, change_id))
}

fn rollback_task_import_index(root: &Path, paths: &[PathBuf], error: ZdevError) -> ZdevError {
    let relative = match relative_paths(root, paths) {
        Ok(relative) => relative,
        Err(rollback) => {
            return ZdevError::new(format!(
                "{error}; cannot identify staged task paths during rollback: {rollback}"
            ));
        }
    };
    let mut reset = ProcessCommand::new("git");
    reset.args(["reset", "-q", "HEAD", "--"]).args(&relative);
    match reset
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
    {
        Ok(output) if output.status.success() => error,
        Ok(output) => ZdevError::new(format!(
            "{error}; cannot unstage imported task paths during rollback: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )),
        Err(rollback) => ZdevError::new(format!(
            "{error}; cannot run Git to unstage imported task paths during rollback: {rollback}"
        )),
    }
}

fn render_draft(header: &TaskHeader, draft: &TaskDraft) -> Result<String, ZdevError> {
    let context = draft
        .context
        .as_deref()
        .map_or_else(String::new, |context| {
            format!("\n\n## Context\n\n{}", context.trim())
        });
    let boundaries = if draft.boundaries.is_empty() {
        String::new()
    } else {
        format!(
            "\n\n## Boundaries\n\n{}",
            draft
                .boundaries
                .iter()
                .map(|item| format!("- {item}"))
                .collect::<Vec<_>>()
                .join("\n")
        )
    };
    let validation = if draft.validation.is_empty() {
        "- Let the verifier choose the smallest useful checks.".to_owned()
    } else {
        draft
            .validation
            .iter()
            .map(|item| format!("- {item}"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    Ok(format!(
        "+++\n{}+++\n# {}\n\n## Outcome\n\n{}{}{}\n\n## Done when\n\n{}\n\n## Validation\n\n{}\n",
        toml::to_string(header)
            .map_err(|error| ZdevError::new(format!("Cannot render task: {error}")))?,
        draft.title,
        draft.outcome,
        context,
        boundaries,
        draft
            .done_when
            .iter()
            .map(|item| format!("- [ ] {item}"))
            .collect::<Vec<_>>()
            .join("\n"),
        validation,
    ))
}

fn load_tasks(root: &Path, area: &str) -> Result<Vec<Task>, ZdevError> {
    let (_, area_dir) = load_area(root, area)?;
    let tasks_dir = area_dir.join("tasks");
    if !tasks_dir.is_dir() {
        return Err(ZdevError::new(format!(
            "Area {area} has no tasks directory: {}",
            tasks_dir.display()
        )));
    }
    let mut tasks = Vec::new();
    for entry in fs::read_dir(&tasks_dir)
        .map_err(|error| ZdevError::io(format!("Cannot list {}", tasks_dir.display()), error))?
    {
        let entry = entry.map_err(|error| ZdevError::io("Cannot inspect task", error))?;
        let path = entry.path();
        if path.extension() != Some(OsStr::new("md")) {
            continue;
        }
        let content = fs::read_to_string(&path)
            .map_err(|error| ZdevError::io(format!("Cannot read {}", path.display()), error))?;
        tasks.push(parse_task(&content, &path, area)?);
    }
    tasks.sort_by(compare_tasks_by_id);
    validate_graph(&tasks)?;
    Ok(tasks)
}

fn parse_task(content: &str, path: &Path, area: &str) -> Result<Task, ZdevError> {
    let rest = content.strip_prefix("+++\n").ok_or_else(|| {
        ZdevError::new(format!("Task lacks TOML frontmatter: {}", path.display()))
    })?;
    let (frontmatter, body) = rest.split_once("+++\n").ok_or_else(|| {
        ZdevError::new(format!("Task has unclosed frontmatter: {}", path.display()))
    })?;
    let header: TaskHeader = toml::from_str(frontmatter)
        .map_err(|error| ZdevError::new(format!("Invalid task {}: {error}", path.display())))?;
    if header.schema_version != SCHEMA_VERSION || header.area != area {
        return Err(ZdevError::new(format!(
            "Task has invalid area or schema: {}",
            path.display()
        )));
    }
    validate_segment(&header.key, "Task key")?;
    let expected_prefix = format!("{area}-");
    if !header.id.starts_with(&expected_prefix) || parse_number(&header.id).is_err() {
        return Err(ZdevError::new(format!("Invalid task ID: {}", header.id)));
    }
    let title = body
        .lines()
        .find_map(|line| line.strip_prefix("# "))
        .filter(|title| !title.trim().is_empty())
        .ok_or_else(|| ZdevError::new(format!("Task lacks a title: {}", path.display())))?
        .to_owned();
    validate_task_body(body, header.status, path)?;
    Ok(Task {
        header,
        title,
        body: body.to_owned(),
        path: path.to_path_buf(),
    })
}

fn markdown_section<'a>(
    body: &'a str,
    heading: &str,
    path: &Path,
) -> Result<Option<&'a str>, ZdevError> {
    let marker = format!("\n## {heading}\n");
    let matches = body.match_indices(&marker).collect::<Vec<_>>();
    let start = match matches.as_slice() {
        [] => return Ok(None),
        [(start, _)] => start + marker.len(),
        _ => {
            return Err(ZdevError::new(format!(
                "Task repeats ## {heading}: {}",
                path.display()
            )));
        }
    };
    let end = body[start..]
        .find("\n## ")
        .map_or(body.len(), |offset| start + offset);
    Ok(Some(body[start..end].trim()))
}

fn required_markdown_section<'a>(
    body: &'a str,
    heading: &str,
    path: &Path,
) -> Result<&'a str, ZdevError> {
    markdown_section(body, heading, path)?
        .ok_or_else(|| ZdevError::new(format!("Task lacks ## {heading}: {}", path.display())))
}

fn validate_bullet_section(section: &str, heading: &str, path: &Path) -> Result<(), ZdevError> {
    if section.is_empty()
        || section.lines().any(|line| {
            !line.trim().is_empty()
                && line
                    .strip_prefix("- ")
                    .is_none_or(|item| item.trim().is_empty())
        })
    {
        return Err(ZdevError::new(format!(
            "Task ## {heading} must contain a non-empty bullet list: {}",
            path.display()
        )));
    }
    Ok(())
}

fn validate_task_body(body: &str, status: TaskStatus, path: &Path) -> Result<(), ZdevError> {
    let outcome = required_markdown_section(body, "Outcome", path)?;
    if outcome.is_empty() {
        return Err(ZdevError::new(format!(
            "Task ## Outcome is empty: {}",
            path.display()
        )));
    }
    if let Some(boundaries) = markdown_section(body, "Boundaries", path)? {
        validate_bullet_section(boundaries, "Boundaries", path)?;
    }
    let done_when = required_markdown_section(body, "Done when", path)?;
    let conditions = done_when
        .lines()
        .filter(|line| !line.trim().is_empty())
        .collect::<Vec<_>>();
    if conditions.is_empty()
        || conditions.iter().any(|line| {
            ["- [ ] ", "- [x] ", "- [X] "]
                .iter()
                .find_map(|prefix| line.strip_prefix(prefix))
                .is_none_or(|item| item.trim().is_empty())
        })
    {
        return Err(ZdevError::new(format!(
            "Task ## Done when must contain only checklist items: {}",
            path.display()
        )));
    }
    if status == TaskStatus::Done && conditions.iter().any(|line| line.starts_with("- [ ] ")) {
        return Err(ZdevError::new(format!(
            "Done task has unchecked conditions: {}",
            path.display()
        )));
    }
    let validation = required_markdown_section(body, "Validation", path)?;
    validate_bullet_section(validation, "Validation", path)?;
    if status == TaskStatus::Done {
        let result = required_markdown_section(body, "Result", path)?;
        if result.is_empty() {
            return Err(ZdevError::new(format!(
                "Done task has an empty ## Result: {}",
                path.display()
            )));
        }
    }
    Ok(())
}

fn replace_markdown_section(
    body: &str,
    heading: &str,
    path: &Path,
    replace: impl FnOnce(&str) -> String,
) -> Result<String, ZdevError> {
    let marker = format!("\n## {heading}\n");
    let start = body
        .find(&marker)
        .ok_or_else(|| ZdevError::new(format!("Task lacks ## {heading}: {}", path.display())))?
        + marker.len();
    let end = body[start..]
        .find("\n## ")
        .map_or(body.len(), |offset| start + offset);
    let mut updated = String::with_capacity(body.len());
    updated.push_str(&body[..start]);
    updated.push_str(&replace(&body[start..end]));
    updated.push_str(&body[end..]);
    Ok(updated)
}

fn parse_number(id: &str) -> Result<u64, ZdevError> {
    id.rsplit_once('-')
        .and_then(|(_, number)| number.parse().ok())
        .ok_or_else(|| ZdevError::new(format!("Task ID has no numeric suffix: {id}")))
}

fn compare_tasks_by_id(left: &Task, right: &Task) -> std::cmp::Ordering {
    parse_number(&left.header.id)
        .expect("task IDs are validated before sorting")
        .cmp(&parse_number(&right.header.id).expect("task IDs are validated before sorting"))
        .then_with(|| left.header.id.cmp(&right.header.id))
}

fn validate_graph(tasks: &[Task]) -> Result<(), ZdevError> {
    let by_id = tasks
        .iter()
        .map(|task| (task.header.id.as_str(), task))
        .collect::<BTreeMap<_, _>>();
    if by_id.len() != tasks.len() {
        return Err(ZdevError::new("Task IDs must be unique"));
    }
    let keys = tasks
        .iter()
        .map(|task| task.header.key.as_str())
        .collect::<BTreeSet<_>>();
    if keys.len() != tasks.len() {
        return Err(ZdevError::new("Task keys must be unique"));
    }
    for task in tasks {
        let mut seen = BTreeSet::new();
        for blocker in &task.header.blocked_by {
            if blocker == &task.header.id || !seen.insert(blocker) {
                return Err(ZdevError::new(format!(
                    "Invalid blocker on {}",
                    task.header.id
                )));
            }
            if !by_id.contains_key(blocker.as_str()) {
                return Err(ZdevError::new(format!(
                    "Task {} has missing blocker {blocker}",
                    task.header.id
                )));
            }
        }
    }
    fn visit<'a>(
        id: &'a str,
        by_id: &BTreeMap<&'a str, &'a Task>,
        visiting: &mut BTreeSet<&'a str>,
        visited: &mut BTreeSet<&'a str>,
    ) -> Result<(), ZdevError> {
        if visited.contains(id) {
            return Ok(());
        }
        if !visiting.insert(id) {
            return Err(ZdevError::new(format!(
                "Task dependency cycle includes {id}"
            )));
        }
        for blocker in &by_id[id].header.blocked_by {
            visit(blocker, by_id, visiting, visited)?;
        }
        visiting.remove(id);
        visited.insert(id);
        Ok(())
    }
    let mut visiting = BTreeSet::new();
    let mut visited = BTreeSet::new();
    for id in by_id.keys().copied() {
        visit(id, &by_id, &mut visiting, &mut visited)?;
    }
    Ok(())
}

fn task_state(task: &Task, tasks: &[Task]) -> &'static str {
    if task.header.status == TaskStatus::Done {
        return "done";
    }
    let statuses = tasks
        .iter()
        .map(|task| (task.header.id.as_str(), task.header.status))
        .collect::<BTreeMap<_, _>>();
    if task
        .header
        .blocked_by
        .iter()
        .all(|id| statuses.get(id.as_str()) == Some(&TaskStatus::Done))
    {
        "ready"
    } else {
        "blocked"
    }
}

fn views<'a>(root: &Path, tasks: &'a [Task]) -> Vec<TaskView<'a>> {
    tasks
        .iter()
        .map(|task| TaskView {
            id: &task.header.id,
            title: &task.title,
            status: task.header.status.as_str(),
            state: task_state(task, tasks),
            blocked_by: &task.header.blocked_by,
            path: relative(root, &task.path),
        })
        .collect()
}

pub(super) fn list(root: &Path, area: &str) -> Result<CommandOutput, ZdevError> {
    let tasks = load_tasks(root, area)?;
    let task_views = views(root, &tasks);
    let text = if task_views.is_empty() {
        format!("No tasks in {area}")
    } else {
        task_views
            .iter()
            .map(|task| format!("{}  {:7}  {}", task.id, task.state, task.title))
            .collect::<Vec<_>>()
            .join("\n")
    };
    Ok(CommandOutput::new(
        text,
        json!({"schema_version": SCHEMA_VERSION, "area": area, "tasks": task_views}),
    ))
}

fn next_task(tasks: &[Task]) -> Option<&Task> {
    tasks.iter().find(|task| task_state(task, tasks) == "ready")
}

fn select_area(root: &Path, requested: Option<&str>) -> Result<String, ZdevError> {
    if let Some(area) = requested {
        load_area(root, area)?;
        return Ok(area.to_owned());
    }
    let config = read_config(root)?;
    if let Some(area) = config.project.default_area {
        load_area(root, &area)?;
        return Ok(area);
    }
    let mut active = Vec::new();
    for area in list_areas(root)? {
        let tasks = load_tasks(root, &area.tag)?;
        if tasks.is_empty()
            || tasks
                .iter()
                .any(|task| task.header.status == TaskStatus::Open)
        {
            active.push(area.tag);
        }
    }
    match active.as_slice() {
        [only] => Ok(only.clone()),
        [] => Err(ZdevError::new(
            "No area has open work. Create tasks or reopen a completed task first",
        )),
        _ => Err(ZdevError::new(format!(
            "Specify an area with `zdev next <area>`. Open areas: {}",
            active.join(", ")
        ))),
    }
}

pub(super) fn next(root: &Path, requested: Option<&str>) -> Result<CommandOutput, ZdevError> {
    let area = select_area(root, requested)?;
    require_fresh_area_link(root, &area)?;
    let tasks = load_tasks(root, &area)?;
    let Some(task) = next_task(&tasks) else {
        let open = tasks
            .iter()
            .any(|task| task.header.status == TaskStatus::Open);
        let status = if open { "blocked" } else { "complete" };
        return Ok(CommandOutput::new(
            if open {
                format!(
                    "No task is ready in {area}. Complete a blocking task or update the dependencies"
                )
            } else {
                format!("All tasks in {area} are done")
            },
            json!({"schema_version": SCHEMA_VERSION, "area": area, "status": status, "task": Value::Null}),
        ));
    };
    let view = TaskView {
        id: &task.header.id,
        title: &task.title,
        status: task.header.status.as_str(),
        state: "ready",
        blocked_by: &task.header.blocked_by,
        path: relative(root, &task.path),
    };
    Ok(CommandOutput::new(
        format!(
            "{}  {}\n{}",
            task.header.id,
            task.title,
            task.path.display()
        ),
        json!({"schema_version": SCHEMA_VERSION, "area": area, "status": "ready", "task": view}),
    ))
}

pub(super) fn show(root: &Path, area: &str, id: &str) -> Result<CommandOutput, ZdevError> {
    let tasks = load_tasks(root, area)?;
    let task = find_task(&tasks, id)?;
    Ok(CommandOutput::new(
        fs::read_to_string(&task.path).map_err(|error| {
            ZdevError::io(format!("Cannot read {}", task.path.display()), error)
        })?,
        json!({
            "schema_version": SCHEMA_VERSION,
            "area": area,
            "id": task.header.id,
            "title": task.title,
            "status": task.header.status.as_str(),
            "state": task_state(task, &tasks),
            "blocked_by": task.header.blocked_by,
            "path": relative(root, &task.path),
            "body": task.body,
        }),
    ))
}

fn find_task<'a>(tasks: &'a [Task], id: &str) -> Result<&'a Task, ZdevError> {
    tasks
        .iter()
        .find(|task| task.header.id == id)
        .ok_or_else(|| ZdevError::new(format!("Unknown task: {id}")))
}

pub(super) fn complete(
    root: &Path,
    area: &str,
    id: &str,
    summary: &str,
    validation: &[String],
) -> Result<CommandOutput, ZdevError> {
    require_fresh_area_link(root, area)?;
    validate_nonempty_line(summary, "Completion summary")?;
    for item in validation {
        validate_nonempty_line(item, "Validation result")?;
    }
    let _lock = ZdevStateLock::acquire(root)?;
    let tasks = load_tasks(root, area)?;
    let task = find_task(&tasks, id)?;
    if task.header.status == TaskStatus::Done {
        return Ok(CommandOutput::new(
            format!("Task {id} is already done"),
            json!({"schema_version": SCHEMA_VERSION, "status": "unchanged", "area": area, "task": id}),
        ));
    }
    if task_state(task, &tasks) != "ready" {
        return Err(ZdevError::new(format!(
            "Cannot complete task {id}: it is blocked. Complete its blockers first"
        )));
    }
    let mut header = task.header.clone();
    header.status = TaskStatus::Done;
    let mut body = replace_markdown_section(&task.body, "Done when", &task.path, |section| {
        section.replace("- [ ] ", "- [x] ")
    })?;
    if !body.ends_with('\n') {
        body.push('\n');
    }
    body.push_str("\n## Result\n\n");
    body.push_str(summary);
    body.push_str("\n\nValidation:\n\n");
    for item in validation {
        body.push_str(&format!("- {item}\n"));
    }
    let content = format!("+++\n{}+++\n{}", toml::to_string(&header).unwrap(), body);
    publish_task_and_index(root, area, task, &content)?;
    Ok(CommandOutput::new(
        format!("Completed task {id}"),
        json!({"schema_version": SCHEMA_VERSION, "status": "done", "area": area, "task": id}),
    ))
}

pub(super) fn reopen(root: &Path, area: &str, id: &str) -> Result<CommandOutput, ZdevError> {
    let _lock = ZdevStateLock::acquire(root)?;
    let tasks = load_tasks(root, area)?;
    let task = find_task(&tasks, id)?;
    if task.header.status == TaskStatus::Open {
        return Ok(CommandOutput::new(
            format!("Task {id} is already open"),
            json!({"schema_version": SCHEMA_VERSION, "status": "unchanged", "area": area, "task": id}),
        ));
    }
    if tasks.iter().any(|candidate| {
        candidate.header.status == TaskStatus::Done
            && candidate
                .header
                .blocked_by
                .iter()
                .any(|blocker| blocker == id)
    }) {
        return Err(ZdevError::new(format!(
            "Cannot reopen {id}: a completed task depends on it. Reopen dependent completed tasks first"
        )));
    }
    let mut header = task.header.clone();
    header.status = TaskStatus::Open;
    let body = task
        .body
        .split("\n## Result\n")
        .next()
        .unwrap_or(&task.body);
    let body = replace_markdown_section(body, "Done when", &task.path, |section| {
        section
            .replace("- [x] ", "- [ ] ")
            .replace("- [X] ", "- [ ] ")
    })?;
    let content = format!("+++\n{}+++\n{}", toml::to_string(&header).unwrap(), body);
    publish_task_and_index(root, area, task, &content)?;
    Ok(CommandOutput::new(
        format!("Reopened task {id}"),
        json!({"schema_version": SCHEMA_VERSION, "status": "open", "area": area, "task": id}),
    ))
}

fn publish_task_and_index(
    root: &Path,
    area: &str,
    current: &Task,
    content: &str,
) -> Result<(), ZdevError> {
    let index_path = root.join(".zdev").join(area).join("TASKS.md");
    let original_task = fs::read(&current.path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", current.path.display()), error))?;
    let original_index = fs::read(&index_path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", index_path.display()), error))?;
    let mut tasks = load_tasks(root, area)?;
    let updated = parse_task(content, &current.path, area)?;
    let slot = tasks
        .iter_mut()
        .find(|task| task.header.id == current.header.id)
        .ok_or_else(|| ZdevError::new(format!("Unknown task: {}", current.header.id)))?;
    *slot = updated;
    let index = render_index(area, &tasks)?;

    write_atomic(&current.path, content.as_bytes())?;
    if let Err(error) = write_atomic(&index_path, index.as_bytes()) {
        let task_rollback = write_atomic(&current.path, &original_task);
        let index_rollback = write_atomic(&index_path, &original_index);
        if let Err(rollback) = task_rollback.and(index_rollback) {
            return Err(ZdevError::new(format!(
                "{error}; rollback also failed: {rollback}"
            )));
        }
        return Err(error);
    }
    Ok(())
}

fn render_index(area: &str, tasks: &[Task]) -> Result<String, ZdevError> {
    validate_graph(tasks)?;
    let ready = tasks
        .iter()
        .filter(|task| task_state(task, tasks) == "ready")
        .count();
    let blocked = tasks
        .iter()
        .filter(|task| task_state(task, tasks) == "blocked")
        .count();
    let done = tasks
        .iter()
        .filter(|task| task.header.status == TaskStatus::Done)
        .count();
    let mut result = format!(
        "{GENERATED_MARKER}\n\n# Tasks: {area}\n\n- Total: {}\n- Ready: {ready}\n- Blocked: {blocked}\n- Done: {done}\n\n| ID | Task | State | Blocked by |\n| --- | --- | --- | --- |\n",
        tasks.len()
    );
    for task in tasks {
        let blockers = if task.header.blocked_by.is_empty() {
            "—".to_owned()
        } else {
            task.header.blocked_by.join(", ")
        };
        let filename = task
            .path
            .file_name()
            .and_then(OsStr::to_str)
            .unwrap_or("task.md");
        result.push_str(&format!(
            "| [{}](tasks/{filename}) | {} | {} | {blockers} |\n",
            task.header.id,
            table_text(&task.title),
            task_state(task, tasks),
        ));
    }
    Ok(result)
}

pub(super) fn empty_index(area: &str) -> Result<String, ZdevError> {
    render_index(area, &[])
}

fn write_index(root: &Path, area: &str) -> Result<PathBuf, ZdevError> {
    let (_, area_dir) = load_area(root, area)?;
    let tasks = load_tasks(root, area)?;
    let path = area_dir.join("TASKS.md");
    write_atomic(&path, render_index(area, &tasks)?.as_bytes())?;
    Ok(path)
}

pub(super) fn index(root: &Path, area: &str) -> Result<CommandOutput, ZdevError> {
    let _lock = ZdevStateLock::acquire(root)?;
    let path = write_index(root, area)?;
    Ok(CommandOutput::new(
        format!("Updated {}", relative(root, &path)),
        json!({"schema_version": SCHEMA_VERSION, "status": "updated", "area": area, "path": relative(root, &path)}),
    ))
}

pub(super) struct AreaTaskSummary {
    pub total: usize,
    pub ready: usize,
    pub blocked: usize,
    pub done: usize,
    pub open: usize,
    pub next: Option<String>,
}

pub(super) fn summary(root: &Path, area: &str) -> Result<AreaTaskSummary, ZdevError> {
    let tasks = load_tasks(root, area)?;
    let ready = tasks
        .iter()
        .filter(|task| task_state(task, &tasks) == "ready")
        .count();
    let blocked = tasks
        .iter()
        .filter(|task| task_state(task, &tasks) == "blocked")
        .count();
    let done = tasks
        .iter()
        .filter(|task| task.header.status == TaskStatus::Done)
        .count();
    Ok(AreaTaskSummary {
        total: tasks.len(),
        ready,
        blocked,
        done,
        open: tasks.len() - done,
        next: next_task(&tasks).map(|task| task.header.id.clone()),
    })
}

pub(super) fn validate_index(root: &Path, area: &str) -> Result<(), ZdevError> {
    let tasks = load_tasks(root, area)?;
    let expected = render_index(area, &tasks)?;
    let path = root.join(".zdev").join(area).join("TASKS.md");
    let actual = fs::read_to_string(&path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", path.display()), error))?;
    if actual != expected {
        return Err(ZdevError::new(format!(
            "Generated task summary is stale: {}",
            path.display()
        )));
    }
    Ok(())
}

fn slug(value: &str) -> String {
    let mut slug = String::new();
    let mut separator = false;
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric() {
            if separator && !slug.is_empty() {
                slug.push('-');
            }
            slug.push(char::from(byte.to_ascii_lowercase()));
            separator = false;
        } else if !slug.is_empty() {
            separator = true;
        }
    }
    if slug.is_empty() {
        "task".to_owned()
    } else {
        slug.truncate(60);
        slug.trim_end_matches('-').to_owned()
    }
}

fn table_text(value: &str) -> String {
    value.replace('|', "\\|")
}
