use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsStr;
use std::fs::{self, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use super::project::{
    AreaLifecycle, AreaMetadata, area_branch_status, current_branch, list_areas, load_area,
    read_config, require_checked_out_area_branch, require_task_work_area_link, slice_briefs,
};
use super::{
    CHANGE_ID_TRAILER, CommandOutput, SCHEMA_VERSION, ZdevError, ZdevStateLock, generate_change_id,
    git_operation, git_output, relative, validate_brief, validate_nonempty_line, validate_segment,
    write_atomic,
};

const GENERATED_MARKER: &str = "<!-- Generated by zdev. Edit task files, not this summary. -->";

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum TaskStatus {
    Open,
    Done,
}

impl TaskStatus {
    fn as_str(self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Done => "done",
        }
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub(super) enum TaskComplexity {
    Routine,
    Standard,
    Advanced,
}

impl TaskComplexity {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Routine => "routine",
            Self::Standard => "standard",
            Self::Advanced => "advanced",
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct TaskHeader {
    schema_version: u64,
    id: String,
    key: String,
    area: String,
    status: TaskStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    complexity: Option<TaskComplexity>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    slice: Option<String>,
    #[serde(default)]
    blocked_by: Vec<String>,
}

#[derive(Clone, Debug)]
struct Task {
    header: TaskHeader,
    title: String,
    body: String,
    path: PathBuf,
}

impl Task {
    fn complexity(&self) -> TaskComplexity {
        self.header.complexity.unwrap_or(TaskComplexity::Standard)
    }
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct TaskBundle {
    schema_version: u64,
    area: String,
    tasks: Vec<TaskDraft>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct TaskDraft {
    key: String,
    title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    complexity: Option<TaskComplexity>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    slice: Option<String>,
    #[serde(default)]
    blocked_by: Vec<String>,
    outcome: String,
    context: Option<String>,
    #[serde(default)]
    boundaries: Vec<String>,
    done_when: Vec<String>,
    #[serde(default)]
    validation: Vec<String>,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
enum DerivedProposalKind {
    #[serde(rename = "investigation_follow_up")]
    InvestigationFollowUp,
    #[serde(rename = "implementation_split")]
    ImplementationSplit,
}

impl DerivedProposalKind {
    fn as_str(self) -> &'static str {
        match self {
            Self::InvestigationFollowUp => "investigation_follow_up",
            Self::ImplementationSplit => "implementation_split",
        }
    }
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct DerivedSourceResult {
    status: String,
    summary: String,
    validation: Vec<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct DerivedChildPaths {
    key: String,
    paths: Vec<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct SplitOwnership {
    retained_parent_paths: Vec<String>,
    child_future_paths: Vec<DerivedChildPaths>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct DerivedProposal {
    schema_version: u64,
    proposal: DerivedProposalKind,
    area: String,
    source_task: String,
    source_result: DerivedSourceResult,
    tasks: Vec<TaskDraft>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    split_ownership: Option<SplitOwnership>,
}

#[derive(Serialize)]
struct TaskView<'a> {
    id: &'a str,
    title: &'a str,
    status: &'static str,
    state: &'static str,
    complexity: TaskComplexity,
    blocked_by: &'a [String],
    slice: Option<&'a str>,
    slice_brief: Option<String>,
    path: String,
}

fn read_task_bundle(source: &Path) -> Result<TaskBundle, ZdevError> {
    let bytes = if source == Path::new("-") {
        let mut bytes = Vec::new();
        io::stdin()
            .read_to_end(&mut bytes)
            .map_err(|error| ZdevError::io("Cannot read task bundle from standard input", error))?;
        bytes
    } else {
        fs::read(source)
            .map_err(|error| ZdevError::io(format!("Cannot read {}", source.display()), error))?
    };
    serde_json::from_slice(&bytes)
        .map_err(|error| ZdevError::new(format!("Invalid task bundle: {error}")))
}

fn validate_task_bundle(root: &Path, bundle: &TaskBundle, area: &str) -> Result<(), ZdevError> {
    if bundle.schema_version != SCHEMA_VERSION || bundle.area != area {
        return Err(ZdevError::new(
            "Task bundle does not match the selected area",
        ));
    }
    if bundle.tasks.is_empty() {
        return Err(ZdevError::new("Task bundle contains no tasks"));
    }
    let slices = slice_briefs(root, area)?;
    let slice_keys = slices
        .iter()
        .map(|slice| slice.key.as_str())
        .collect::<BTreeSet<_>>();
    let mut seen_keys = BTreeSet::new();
    for task in &bundle.tasks {
        validate_segment(&task.key, "Task key")?;
        validate_nonempty_line(&task.title, "Task title")?;
        validate_nonempty_line(&task.outcome, "Task outcome")?;
        if let Some(slice) = &task.slice {
            validate_segment(slice, "Slice key")?;
            if !slice_keys.contains(slice.as_str()) {
                return Err(ZdevError::new(format!(
                    "Task {} references unknown slice {slice}",
                    task.key
                )));
            }
        }
        if task
            .context
            .as_deref()
            .is_some_and(|context| context.trim().is_empty())
        {
            return Err(ZdevError::new(format!(
                "Task {} has empty context",
                task.key
            )));
        }
        if task.done_when.is_empty() {
            return Err(ZdevError::new(format!(
                "Task {} has no done conditions",
                task.key
            )));
        }
        if !seen_keys.insert(task.key.as_str()) {
            return Err(ZdevError::new(format!("Duplicate task key: {}", task.key)));
        }
    }
    Ok(())
}

fn task_bundle_approval_id(bundle: &TaskBundle) -> Result<String, ZdevError> {
    let canonical = serde_json::to_vec(bundle)
        .map_err(|error| ZdevError::new(format!("Cannot fingerprint task bundle: {error}")))?;
    let hash = canonical.iter().fold(0xcbf29ce484222325_u64, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)
    });
    Ok(format!("T{hash:016x}"))
}

fn approval_value(value: Option<&str>) -> &str {
    value.filter(|value| !value.is_empty()).unwrap_or("None")
}

fn approval_list(values: &[String]) -> String {
    if values.is_empty() {
        "None".to_owned()
    } else {
        values
            .iter()
            .enumerate()
            .map(|(index, value)| format!("{}. {value}", index + 1))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

fn longest_backtick_run(value: &str) -> usize {
    value
        .split(|character| character != '`')
        .map(str::len)
        .max()
        .unwrap_or(0)
}

fn render_task_bundle_approval(bundle: &TaskBundle) -> String {
    let mut document = format!(
        "# Task Bundle\n\n## Area\n{}\n\n## Schema version\n{}",
        bundle.area, bundle.schema_version
    );
    for (index, task) in bundle.tasks.iter().enumerate() {
        document.push_str(&format!(
            "\n\n## Task {}\n\n### Key\n{}\n\n### Title\n{}",
            index + 1,
            task.key,
            task.title,
        ));
        if let Some(complexity) = task.complexity {
            document.push_str(&format!("\n\n### Complexity\n{}", complexity.as_str()));
        }
        document.push_str(&format!(
            "\n\n### Slice\n{}\n\n### Outcome\n{}\n\n### Context\n{}\n\n### Boundaries\n{}\n\n### Blocked by\n{}\n\n### Done when / proof\n{}\n\n### Validation / Testing\n{}",
            approval_value(task.slice.as_deref()),
            task.outcome,
            approval_value(task.context.as_deref()),
            approval_list(&task.boundaries),
            approval_list(&task.blocked_by),
            approval_list(&task.done_when),
            approval_list(&task.validation),
        ));
    }
    let fence = "`".repeat(longest_backtick_run(&document).saturating_add(1).max(3));
    format!("{fence}markdown\n{document}\n{fence}")
}

pub(super) fn review(root: &Path, area: &str, source: &Path) -> Result<CommandOutput, ZdevError> {
    load_area(root, area)?;
    let bundle = read_task_bundle(source)?;
    validate_task_bundle(root, &bundle, area)?;
    let approval = task_bundle_approval_id(&bundle)?;
    let markdown = render_task_bundle_approval(&bundle);
    Ok(CommandOutput::new(
        markdown.clone(),
        json!({
            "schema_version": SCHEMA_VERSION,
            "status": "reviewed",
            "area": area,
            "approval": approval,
            "markdown": markdown,
        }),
    ))
}

fn read_derived_proposal(source: &Path) -> Result<DerivedProposal, ZdevError> {
    let bytes = if source == Path::new("-") {
        let mut bytes = Vec::new();
        io::stdin().read_to_end(&mut bytes).map_err(|error| {
            ZdevError::io("Cannot read derived proposal from standard input", error)
        })?;
        bytes
    } else {
        fs::read(source)
            .map_err(|error| ZdevError::io(format!("Cannot read {}", source.display()), error))?
    };
    let input = std::str::from_utf8(&bytes)
        .map_err(|error| ZdevError::new(format!("Invalid derived proposal UTF-8: {error}")))?;
    let (first_line, json) = input.split_once('\n').ok_or_else(|| {
        ZdevError::new("Invalid derived proposal: expected an identity line and one JSON object")
    })?;
    let proposal: DerivedProposal = serde_json::from_str(json)
        .map_err(|error| ZdevError::new(format!("Invalid derived proposal: {error}")))?;
    let expected = format!(
        "PROPOSE zdev-derived {} {}",
        proposal.area, proposal.source_task
    );
    if first_line != expected {
        return Err(ZdevError::new(format!(
            "Derived proposal identity line does not match its area and source task; expected `{expected}`"
        )));
    }
    Ok(proposal)
}

fn validate_derived_proposal(
    root: &Path,
    proposal: &DerivedProposal,
    area: &str,
) -> Result<TaskBundle, ZdevError> {
    if proposal.schema_version != SCHEMA_VERSION || proposal.area != area {
        return Err(ZdevError::new(
            "Derived proposal does not match the selected area",
        ));
    }
    if proposal.tasks.is_empty() || proposal.tasks.len() > 5 {
        return Err(ZdevError::new(
            "Derived proposal must contain between one and five tasks",
        ));
    }
    validate_nonempty_line(&proposal.source_result.summary, "Source result summary")?;
    for validation in &proposal.source_result.validation {
        validate_nonempty_line(validation, "Source result validation")?;
    }
    match proposal.proposal {
        DerivedProposalKind::InvestigationFollowUp => {
            if proposal.source_result.status != "complete"
                || proposal.source_result.validation.is_empty()
                || proposal.split_ownership.is_some()
            {
                return Err(ZdevError::new(
                    "Investigation follow-up requires a complete validated source result and forbids split ownership",
                ));
            }
        }
        DerivedProposalKind::ImplementationSplit => {
            if proposal.source_result.status != "split"
                || !proposal.source_result.validation.is_empty()
                || proposal.split_ownership.is_none()
            {
                return Err(ZdevError::new(
                    "Implementation split requires a split source result with empty validation and exact split ownership",
                ));
            }
        }
    }

    let bundle = TaskBundle {
        schema_version: proposal.schema_version,
        area: proposal.area.clone(),
        tasks: proposal.tasks.clone(),
    };
    validate_task_bundle(root, &bundle, area)?;
    let existing = load_tasks(root, area)?;
    let existing_ids = existing
        .iter()
        .map(|task| task.header.id.as_str())
        .collect::<BTreeSet<_>>();
    let existing_keys = existing
        .iter()
        .map(|task| task.header.key.as_str())
        .collect::<BTreeSet<_>>();
    if !existing_ids.contains(proposal.source_task.as_str()) {
        return Err(ZdevError::new(format!(
            "Derived proposal source task {} does not exist in area {area}",
            proposal.source_task
        )));
    }
    let proposed_keys = bundle
        .tasks
        .iter()
        .map(|task| task.key.as_str())
        .collect::<BTreeSet<_>>();
    for task in &bundle.tasks {
        if existing_keys.contains(task.key.as_str()) {
            return Err(ZdevError::new(format!("Duplicate task key: {}", task.key)));
        }
        for blocker in &task.blocked_by {
            if blocker == &proposal.source_task {
                return Err(ZdevError::new(format!(
                    "Derived task {} cannot be blocked by its source task",
                    task.key
                )));
            }
            if !existing_ids.contains(blocker.as_str()) && !proposed_keys.contains(blocker.as_str())
            {
                return Err(ZdevError::new(format!(
                    "Derived task {} has unknown blocker {blocker}",
                    task.key
                )));
            }
        }
    }
    validate_derived_dependencies(&bundle.tasks)?;
    if let Some(ownership) = &proposal.split_ownership {
        validate_split_ownership(root, &bundle.tasks, ownership)?;
    }
    Ok(bundle)
}

fn validate_derived_dependencies(tasks: &[TaskDraft]) -> Result<(), ZdevError> {
    let proposed = tasks
        .iter()
        .map(|task| task.key.as_str())
        .collect::<BTreeSet<_>>();
    let mut remaining = tasks
        .iter()
        .map(|task| {
            (
                task.key.as_str(),
                task.blocked_by
                    .iter()
                    .map(String::as_str)
                    .filter(|blocker| proposed.contains(blocker))
                    .collect::<BTreeSet<_>>(),
            )
        })
        .collect::<BTreeMap<_, _>>();
    loop {
        let ready = remaining
            .iter()
            .filter_map(|(key, blockers)| blockers.is_empty().then_some(*key))
            .collect::<Vec<_>>();
        if ready.is_empty() {
            break;
        }
        for key in &ready {
            remaining.remove(key);
        }
        for blockers in remaining.values_mut() {
            for key in &ready {
                blockers.remove(key);
            }
        }
    }
    if remaining.is_empty() {
        Ok(())
    } else {
        Err(ZdevError::new(
            "Derived proposal contains a cyclic or self dependency",
        ))
    }
}

fn validate_derived_path(root: &Path, value: &str, must_exist: bool) -> Result<(), ZdevError> {
    validate_nonempty_line(value, "Derived ownership path")?;
    if matches!(value.split('/').next(), Some(".git" | ".zdev")) {
        return Err(ZdevError::new(format!(
            "Derived ownership path cannot name repository control or zdev managed state: {value}"
        )));
    }
    if value.contains('\\')
        || value.starts_with('/')
        || value.ends_with('/')
        || value.contains("//")
        || value
            .split('/')
            .any(|part| part.is_empty() || part == "." || part == "..")
    {
        return Err(ZdevError::new(format!(
            "Derived ownership path is not normalized and repository-relative: {value}"
        )));
    }
    let path = root.join(value);
    let mut current = root.to_path_buf();
    let parts = value.split('/').collect::<Vec<_>>();
    for part in &parts[..parts.len().saturating_sub(1)] {
        current.push(part);
        let metadata = fs::symlink_metadata(&current).map_err(|error| {
            ZdevError::io(
                format!("Cannot inspect ownership path parent {}", current.display()),
                error,
            )
        })?;
        if metadata.file_type().is_symlink() || !metadata.is_dir() {
            return Err(ZdevError::new(format!(
                "Derived ownership path has a non-directory or symlinked parent: {value}"
            )));
        }
    }
    match fs::symlink_metadata(&path) {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
            Err(ZdevError::new(format!(
                "Derived ownership path is not a regular file: {value}"
            )))
        }
        Ok(_) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound && !must_exist => Ok(()),
        Err(error) => Err(ZdevError::io(
            format!("Cannot inspect derived ownership path {}", path.display()),
            error,
        )),
    }
}

fn validate_split_ownership(
    root: &Path,
    tasks: &[TaskDraft],
    ownership: &SplitOwnership,
) -> Result<(), ZdevError> {
    let task_keys = tasks
        .iter()
        .map(|task| task.key.as_str())
        .collect::<BTreeSet<_>>();
    let child_keys = ownership
        .child_future_paths
        .iter()
        .map(|child| child.key.as_str())
        .collect::<BTreeSet<_>>();
    if child_keys.len() != ownership.child_future_paths.len() || child_keys != task_keys {
        return Err(ZdevError::new(
            "Split ownership must name every proposed task key exactly once",
        ));
    }
    let mut paths = BTreeSet::new();
    for path in &ownership.retained_parent_paths {
        if !paths.insert(path.as_str()) {
            return Err(ZdevError::new(format!(
                "Duplicate split ownership path: {path}"
            )));
        }
        validate_derived_path(root, path, true)?;
    }
    for child in &ownership.child_future_paths {
        if child.paths.is_empty() {
            return Err(ZdevError::new(format!(
                "Split ownership for {} contains no future paths",
                child.key
            )));
        }
        for path in &child.paths {
            if !paths.insert(path.as_str()) {
                return Err(ZdevError::new(format!(
                    "Split ownership path is duplicated or overlaps another owner: {path}"
                )));
            }
            validate_derived_path(root, path, false)?;
        }
    }
    Ok(())
}

fn git_nul_paths(root: &Path, arguments: &[&str]) -> Result<BTreeSet<String>, ZdevError> {
    let output = ProcessCommand::new("git")
        .args(arguments)
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
        .map_err(|error| ZdevError::io("Cannot inspect Git paths for derived proposal", error))?;
    if !output.status.success() {
        return Err(ZdevError::new(format!(
            "Cannot inspect Git paths for derived proposal: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let stdout = std::str::from_utf8(&output.stdout)
        .map_err(|error| ZdevError::new(format!("Git returned a non-UTF-8 path: {error}")))?;
    Ok(stdout
        .split('\0')
        .filter(|path| !path.is_empty())
        .map(str::to_owned)
        .collect())
}

fn derived_mechanical_ineligibility(
    root: &Path,
    proposal: &DerivedProposal,
) -> Result<Option<String>, ZdevError> {
    let (area, _) = load_area(root, &proposal.area)?;
    if area.lifecycle == AreaLifecycle::Closed {
        return Ok(Some(format!("area {} is closed", proposal.area)));
    }
    let tasks = load_tasks(root, &proposal.area)?;
    let source = tasks
        .iter()
        .find(|task| task.header.id == proposal.source_task)
        .expect("validated derived source task");
    if source.header.status != TaskStatus::Open {
        return Ok(Some(format!(
            "source task {} is not open",
            proposal.source_task
        )));
    }
    if next_task(&tasks).map(|task| task.header.id.as_str()) != Some(proposal.source_task.as_str())
    {
        return Ok(Some(format!(
            "source task {} is not the current ready task",
            proposal.source_task
        )));
    }
    if let Err(error) = require_task_work_area_link(root, &proposal.area) {
        return Ok(Some(error.to_string()));
    }
    if let Some(ownership) = &proposal.split_ownership {
        let staged = git_nul_paths(root, &["diff", "--cached", "--name-only", "-z"])?;
        if !staged.is_empty() {
            return Ok(Some(
                "the index is not empty, so split ownership needs manual review".to_owned(),
            ));
        }
        let mut unstaged = git_nul_paths(root, &["diff", "--name-only", "-z"])?;
        unstaged.extend(git_nul_paths(
            root,
            &["ls-files", "--others", "--exclude-standard", "-z"],
        )?);
        let retained = ownership
            .retained_parent_paths
            .iter()
            .cloned()
            .collect::<BTreeSet<_>>();
        if unstaged != retained {
            return Ok(Some(
                "retained parent paths do not equal the checkout's complete unstaged path set"
                    .to_owned(),
            ));
        }
    }
    Ok(None)
}

fn derived_approval_id(proposal: &DerivedProposal) -> Result<String, ZdevError> {
    let canonical = serde_json::to_vec(proposal)
        .map_err(|error| ZdevError::new(format!("Cannot fingerprint derived proposal: {error}")))?;
    let hash = canonical.iter().fold(0xcbf29ce484222325_u64, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)
    });
    Ok(format!("D{hash:016x}"))
}

pub(super) fn review_derived(
    root: &Path,
    area: &str,
    source: &Path,
) -> Result<CommandOutput, ZdevError> {
    let proposal = read_derived_proposal(source)?;
    let bundle = validate_derived_proposal(root, &proposal, area)?;
    let reason = derived_mechanical_ineligibility(root, &proposal)?;
    let approval = derived_approval_id(&proposal)?;
    let markdown = render_task_bundle_approval(&bundle);
    let canonical = serde_json::to_string_pretty(&proposal)
        .map_err(|error| ZdevError::new(format!("Cannot render derived proposal: {error}")))?;
    if let Some(reason) = reason {
        let text = format!(
            "Mechanical authority unavailable: {reason}\n\nPROPOSE zdev-derived {} {}\n{}\n\n{markdown}\n\nApproval: {approval}",
            proposal.area, proposal.source_task, canonical
        );
        return Ok(CommandOutput::new(
            text,
            json!({
                "schema_version": SCHEMA_VERSION,
                "status": "reviewed",
                "area": area,
                "source_task": proposal.source_task,
                "proposal": proposal.proposal.as_str(),
                "envelope": proposal,
                "mechanically_eligible": false,
                "coordinator_authority_required": true,
                "reason": reason,
                "approval": approval,
                "markdown": markdown,
            }),
        ));
    }
    let text = format!(
        "Mechanically eligible for automatic authority. The coordinator must still confirm unchanged handoff evidence and direct in-scope authority.\n\nPROPOSE zdev-derived {} {}\n{}",
        proposal.area, proposal.source_task, canonical
    );
    Ok(CommandOutput::new(
        text,
        json!({
            "schema_version": SCHEMA_VERSION,
            "status": "reviewed",
            "area": area,
            "source_task": proposal.source_task,
            "proposal": proposal.proposal.as_str(),
            "envelope": proposal,
            "mechanically_eligible": true,
            "coordinator_authority_required": true,
            "approval": approval,
            "markdown": markdown,
        }),
    ))
}

pub(super) fn apply_derived(
    root: &Path,
    area: &str,
    source: &Path,
    approval: Option<&str>,
) -> Result<CommandOutput, ZdevError> {
    let proposal = read_derived_proposal(source)?;
    validate_derived_proposal(root, &proposal, area)?;
    if let Some(approval) = approval
        && approval != derived_approval_id(&proposal)?
    {
        return Err(ZdevError::new(
            "Derived proposal differs from the reviewed content; run `zdev tasks derive review` again before applying it",
        ));
    }

    let _lock = ZdevStateLock::acquire(root)?;
    let bundle = validate_derived_proposal(root, &proposal, area)?;
    if let Some(reason) = derived_mechanical_ineligibility(root, &proposal)? {
        return Err(ZdevError::new(format!(
            "Cannot apply derived proposal automatically: {reason}. Use `zdev tasks derive review` for manual review"
        )));
    }
    if let Some(operation) = git_operation(root)? {
        return Err(ZdevError::new(format!(
            "Cannot apply derived proposal while a {operation} is in progress. Finish or abort it, then retry"
        )));
    }
    git_output(root, &["rev-parse", "--verify", "HEAD"]).map_err(|_| {
        ZdevError::new("Cannot apply derived proposal before the repository has a commit")
    })?;

    let (metadata, area_dir) = load_area(root, area)?;
    require_checked_out_area_branch(root, &metadata)?;
    let existing = load_tasks(root, area)?;
    let source_task = find_task(&existing, &proposal.source_task)?;
    if proposal.proposal == DerivedProposalKind::ImplementationSplit {
        for draft in &bundle.tasks {
            if draft.slice.as_ref() != source_task.header.slice.as_ref() && draft.slice.is_some() {
                return Err(ZdevError::new(format!(
                    "Split task {} must inherit source task slice {}",
                    draft.key,
                    source_task.header.slice.as_deref().unwrap_or("None")
                )));
            }
        }
    }

    let prior_index = git_output(root, &["write-tree"])?;
    let prior_staged = git_nul_paths(root, &["diff", "--cached", "--name-only", "-z"])?;
    let mut unstaged = git_nul_paths(root, &["diff", "--name-only", "-z"])?;
    unstaged.extend(git_nul_paths(
        root,
        &["ls-files", "--others", "--exclude-standard", "-z"],
    )?);
    if proposal.proposal == DerivedProposalKind::InvestigationFollowUp {
        for path in &prior_staged {
            validate_derived_path(root, path, true).map_err(|error| {
                ZdevError::new(format!(
                    "Cannot treat staged path {path} as a verified investigation artifact: {error}"
                ))
            })?;
        }
        if !unstaged.is_empty() {
            return Err(ZdevError::new(
                "Cannot apply investigation follow-up with unstaged or untracked paths; stage only its verified task-owned artifact paths first",
            ));
        }
    }

    let existing_ids = existing
        .iter()
        .map(|task| task.header.id.as_str())
        .collect::<BTreeSet<_>>();
    let existing_keys = existing
        .iter()
        .map(|task| task.header.key.as_str())
        .collect::<BTreeSet<_>>();
    for task in &bundle.tasks {
        if existing_keys.contains(task.key.as_str()) {
            return Err(ZdevError::new(format!("Duplicate task key: {}", task.key)));
        }
    }
    let mut next_number = existing
        .iter()
        .filter_map(|task| task.header.id.rsplit_once('-')?.1.parse::<u64>().ok())
        .max()
        .unwrap_or(0);
    let mut allocated = BTreeMap::new();
    for task in &bundle.tasks {
        next_number += 1;
        allocated.insert(task.key.as_str(), format!("{area}-{next_number:03}"));
    }

    let ownership_paths = proposal.split_ownership.as_ref().map(|ownership| {
        ownership
            .child_future_paths
            .iter()
            .map(|child| (child.key.as_str(), child.paths.as_slice()))
            .collect::<BTreeMap<_, _>>()
    });
    let mut writes = Vec::new();
    for draft in &bundle.tasks {
        let id = allocated[draft.key.as_str()].clone();
        let blockers = draft
            .blocked_by
            .iter()
            .map(|blocker| {
                if let Some(id) = allocated.get(blocker.as_str()) {
                    Ok(id.clone())
                } else if existing_ids.contains(blocker.as_str()) {
                    Ok(blocker.clone())
                } else {
                    Err(ZdevError::new(format!(
                        "Task {} has unknown blocker {blocker}",
                        draft.key
                    )))
                }
            })
            .collect::<Result<Vec<_>, _>>()?;
        let header = TaskHeader {
            schema_version: SCHEMA_VERSION,
            id: id.clone(),
            key: draft.key.clone(),
            area: area.to_owned(),
            status: TaskStatus::Open,
            complexity: draft.complexity,
            slice: match proposal.proposal {
                DerivedProposalKind::InvestigationFollowUp => draft.slice.clone(),
                DerivedProposalKind::ImplementationSplit => source_task.header.slice.clone(),
            },
            blocked_by: blockers,
        };
        let path = area_dir.join("tasks").join(format!(
            "{number:03}-{}.md",
            slug(&draft.title),
            number = parse_number(&id)?
        ));
        let mut rendered = draft.clone();
        if let Some(paths) = ownership_paths
            .as_ref()
            .and_then(|paths| paths.get(draft.key.as_str()))
        {
            let paths = serde_json::to_string(paths).map_err(|error| {
                ZdevError::new(format!("Cannot render derived ownership paths: {error}"))
            })?;
            rendered
                .boundaries
                .push(format!("Task-owned paths (exact): {paths}"));
        }
        writes.push((path, render_draft(&header, &rendered)?));
    }

    let mut source_header = source_task.header.clone();
    let source_body = match proposal.proposal {
        DerivedProposalKind::InvestigationFollowUp => {
            source_header.status = TaskStatus::Done;
            let mut body = replace_markdown_section(
                &source_task.body,
                "Done when",
                &source_task.path,
                |section| section.replace("- [ ] ", "- [x] "),
            )?;
            if !body.ends_with('\n') {
                body.push('\n');
            }
            body.push_str("\n## Result\n\n");
            body.push_str(&proposal.source_result.summary);
            body.push_str("\n\nValidation:\n\n");
            for item in &proposal.source_result.validation {
                body.push_str(&format!("- {item}\n"));
            }
            body
        }
        DerivedProposalKind::ImplementationSplit => {
            source_header.blocked_by.extend(
                bundle
                    .tasks
                    .iter()
                    .map(|task| allocated[task.key.as_str()].clone()),
            );
            source_header.blocked_by.sort();
            source_header.blocked_by.dedup();
            source_task.body.clone()
        }
    };
    let source_content = format!(
        "+++\n{}+++\n{}",
        toml::to_string(&source_header)
            .map_err(|error| ZdevError::new(format!("Cannot render source task: {error}")))?,
        source_body
    );

    let mut hypothetical = existing.clone();
    let source_slot = hypothetical
        .iter_mut()
        .find(|task| task.header.id == proposal.source_task)
        .expect("validated source task");
    *source_slot = parse_task(&source_content, &source_task.path, area)?;
    for (path, content) in &writes {
        hypothetical.push(parse_task(content, path, area)?);
    }
    hypothetical.sort_by(compare_tasks_by_id);
    let index_content = render_index(area, &hypothetical)?;
    let ready = hypothetical
        .iter()
        .filter(|task| task_state(task, &hypothetical) == "ready")
        .map(|task| task.header.id.clone())
        .collect::<Vec<_>>();

    let index_path = area_dir.join("TASKS.md");
    let original_source = fs::read(&source_task.path).map_err(|error| {
        ZdevError::io(format!("Cannot read {}", source_task.path.display()), error)
    })?;
    let original_index = fs::read(&index_path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", index_path.display()), error))?;
    let retained = proposal
        .split_ownership
        .as_ref()
        .map(|ownership| {
            ownership
                .retained_parent_paths
                .iter()
                .map(|path| {
                    fs::read(root.join(path))
                        .map(|bytes| (path.clone(), bytes))
                        .map_err(|error| {
                            ZdevError::io(format!("Cannot read retained path {path}"), error)
                        })
                })
                .collect::<Result<Vec<_>, _>>()
        })
        .transpose()?
        .unwrap_or_default();
    let staged_artifacts = prior_staged
        .iter()
        .map(|path| {
            fs::read(root.join(path))
                .map(|bytes| (path.clone(), bytes))
                .map_err(|error| {
                    ZdevError::io(format!("Cannot read staged artifact {path}"), error)
                })
        })
        .collect::<Result<Vec<_>, _>>()?;
    let created = writes
        .iter()
        .map(|(path, _)| path.clone())
        .collect::<Vec<_>>();
    let apply = (|| -> Result<(String, String, Vec<PathBuf>), ZdevError> {
        write_atomic(&source_task.path, source_content.as_bytes())?;
        for (path, content) in &writes {
            let mut file = OpenOptions::new()
                .create_new(true)
                .write(true)
                .open(path)
                .map_err(|error| {
                    ZdevError::io(format!("Cannot create {}", path.display()), error)
                })?;
            file.write_all(content.as_bytes())
                .and_then(|()| file.sync_all())
                .map_err(|error| {
                    ZdevError::io(format!("Cannot write {}", path.display()), error)
                })?;
        }
        write_atomic(&index_path, index_content.as_bytes())?;
        for (path, bytes) in &retained {
            if fs::read(root.join(path)).ok().as_deref() != Some(bytes.as_slice()) {
                return Err(ZdevError::new(format!(
                    "Retained parent path changed before commit: {path}"
                )));
            }
        }
        for (path, bytes) in &staged_artifacts {
            if fs::read(root.join(path)).ok().as_deref() != Some(bytes.as_slice()) {
                return Err(ZdevError::new(format!(
                    "Staged investigation artifact changed before commit: {path}"
                )));
            }
        }
        let mut paths = prior_staged
            .iter()
            .map(|path| root.join(path))
            .collect::<Vec<_>>();
        paths.push(source_task.path.clone());
        paths.extend(created.iter().cloned());
        paths.push(index_path.clone());
        let (revision, change_id) = commit_task_import(root, area, &paths)?;
        Ok((revision, change_id, paths))
    })();

    let (revision, change_id, paths) = match apply {
        Ok(result) => result,
        Err(error) => {
            let mut rollback_errors = Vec::new();
            for path in &created {
                if let Err(rollback) = fs::remove_file(path)
                    && rollback.kind() != io::ErrorKind::NotFound
                {
                    rollback_errors.push(format!("cannot remove {}: {rollback}", path.display()));
                }
            }
            if let Err(rollback) = write_atomic(&source_task.path, &original_source) {
                rollback_errors.push(format!("cannot restore source task: {rollback}"));
            }
            if let Err(rollback) = write_atomic(&index_path, &original_index) {
                rollback_errors.push(format!("cannot restore task index: {rollback}"));
            }
            if let Err(rollback) = git_read_tree(root, &prior_index) {
                rollback_errors.push(format!("cannot restore Git index: {rollback}"));
            }
            for (path, bytes) in &retained {
                if fs::read(root.join(path)).ok().as_deref() != Some(bytes.as_slice())
                    && let Err(rollback) = write_atomic(&root.join(path), bytes)
                {
                    rollback_errors.push(format!("cannot restore {path}: {rollback}"));
                }
            }
            for (path, bytes) in &staged_artifacts {
                if fs::read(root.join(path)).ok().as_deref() != Some(bytes.as_slice())
                    && let Err(rollback) = write_atomic(&root.join(path), bytes)
                {
                    rollback_errors.push(format!("cannot restore {path}: {rollback}"));
                }
            }
            if rollback_errors.is_empty() {
                return Err(ZdevError::new(format!(
                    "Could not apply derived proposal; all task, index, and retained bytes were restored. {error}"
                )));
            }
            return Err(ZdevError::new(format!(
                "Could not apply derived proposal, and rollback was incomplete. {error}. {}",
                rollback_errors.join("; ")
            )));
        }
    };

    let ids = bundle
        .tasks
        .iter()
        .map(|task| allocated[task.key.as_str()].clone())
        .collect::<Vec<_>>();
    let mut value = json!({
        "schema_version": SCHEMA_VERSION,
        "status": "committed",
        "area": area,
        "source_task": proposal.source_task,
        "proposal": proposal.proposal.as_str(),
        "source_result": proposal.source_result,
        "tasks": ids,
        "ready": ready,
        "commit": revision,
        "change_id": change_id,
        "paths": relative_paths(root, &paths)?,
    });
    if let Some(ownership) = proposal.split_ownership {
        value
            .as_object_mut()
            .expect("JSON object")
            .insert("split_ownership".to_owned(), json!(ownership));
    }
    Ok(CommandOutput::new(
        format!("Applied derived tasks to {area} ({revision})"),
        value,
    ))
}

fn git_read_tree(root: &Path, tree: &str) -> Result<(), ZdevError> {
    let output = ProcessCommand::new("git")
        .args(["read-tree", tree])
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
        .map_err(|error| ZdevError::io("Cannot restore Git index", error))?;
    if output.status.success() {
        Ok(())
    } else {
        Err(ZdevError::new(format!(
            "Cannot restore Git index: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )))
    }
}

pub(super) fn import(
    root: &Path,
    area: &str,
    source: &Path,
    commit_changes: bool,
    approval: Option<&str>,
) -> Result<CommandOutput, ZdevError> {
    let bundle = read_task_bundle(source)?;
    validate_task_bundle(root, &bundle, area)?;
    if let Some(approval) = approval {
        let actual = task_bundle_approval_id(&bundle)?;
        if approval != actual {
            return Err(ZdevError::new(
                "Task bundle differs from the reviewed content; run `zdev tasks review` again before importing it",
            ));
        }
    }
    let _lock = ZdevStateLock::acquire(root)?;
    let (metadata, area_dir) = load_area(root, area)?;
    if metadata.lifecycle == AreaLifecycle::Closed {
        return Err(ZdevError::new(format!(
            "Cannot add tasks to closed area {area}. Run `zdev area reopen {area}` first"
        )));
    }
    let committable_brief = if commit_changes {
        require_checked_out_area_branch(root, &metadata)?;
        require_committable_task_import(root, area)?
    } else {
        None
    };
    let existing = load_tasks(root, area)?;
    let existing_ids = existing
        .iter()
        .map(|task| task.header.id.as_str())
        .collect::<BTreeSet<_>>();
    let existing_keys = existing
        .iter()
        .map(|task| task.header.key.as_str())
        .collect::<BTreeSet<_>>();
    for task in &bundle.tasks {
        if existing_keys.contains(task.key.as_str()) {
            return Err(ZdevError::new(format!("Duplicate task key: {}", task.key)));
        }
    }
    let mut next_number = existing
        .iter()
        .filter_map(|task| task.header.id.rsplit_once('-')?.1.parse::<u64>().ok())
        .max()
        .unwrap_or(0);
    let mut allocated = BTreeMap::new();
    for task in &bundle.tasks {
        next_number += 1;
        allocated.insert(task.key.as_str(), format!("{area}-{next_number:03}"));
    }
    let mut writes = Vec::new();
    for draft in &bundle.tasks {
        let id = allocated[&draft.key.as_str()].clone();
        let blockers = draft
            .blocked_by
            .iter()
            .map(|blocker| {
                if let Some(id) = allocated.get(blocker.as_str()) {
                    Ok((*id).clone())
                } else if existing_ids.contains(blocker.as_str()) {
                    Ok(blocker.clone())
                } else {
                    Err(ZdevError::new(format!(
                        "Task {} has unknown blocker {blocker}",
                        draft.key
                    )))
                }
            })
            .collect::<Result<Vec<_>, _>>()?;
        if blockers.iter().any(|blocker| blocker == &id) {
            return Err(ZdevError::new(format!("Task {} blocks itself", draft.key)));
        }
        let header = TaskHeader {
            schema_version: SCHEMA_VERSION,
            id: id.clone(),
            key: draft.key.clone(),
            area: area.to_owned(),
            status: TaskStatus::Open,
            complexity: draft.complexity,
            slice: draft.slice.clone(),
            blocked_by: blockers,
        };
        let path = area_dir.join("tasks").join(format!(
            "{next:03}-{}.md",
            slug(&draft.title),
            next = parse_number(&id)?
        ));
        let body = render_draft(&header, draft)?;
        writes.push((path, body));
    }
    let mut hypothetical = existing.clone();
    for (path, content) in &writes {
        hypothetical.push(parse_task(content, path, area)?);
    }
    hypothetical.sort_by(compare_tasks_by_id);
    validate_graph(&hypothetical)?;
    let ready = hypothetical
        .iter()
        .filter(|task| task_state(task, &hypothetical) == "ready")
        .map(|task| task.header.id.clone())
        .collect::<Vec<_>>();
    let index_path = area_dir.join("TASKS.md");
    let previous_index = fs::read(&index_path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", index_path.display()), error))?;
    let mut created = Vec::new();
    for (path, content) in &writes {
        match OpenOptions::new().create_new(true).write(true).open(path) {
            Ok(mut file) => {
                created.push(path.clone());
                if let Err(error) = file
                    .write_all(content.as_bytes())
                    .and_then(|()| file.sync_all())
                {
                    let write_error =
                        ZdevError::io(format!("Cannot write {}", path.display()), error);
                    drop(file);
                    return Err(import_rollback_error(write_error, &created, None));
                }
            }
            Err(error) => {
                let create_error =
                    ZdevError::io(format!("Cannot create {}", path.display()), error);
                return Err(import_rollback_error(create_error, &created, None));
            }
        }
    }
    if let Err(error) = write_index(root, area) {
        return Err(import_rollback_error(
            error,
            &created,
            commit_changes.then_some((index_path.as_path(), previous_index.as_slice())),
        ));
    }
    let ids = writes
        .iter()
        .map(|(_, content)| {
            parse_task(content, Path::new("task.md"), area).map(|task| task.header.id)
        })
        .collect::<Result<Vec<_>, _>>()?;
    if commit_changes {
        let mut paths = committable_brief.into_iter().collect::<Vec<_>>();
        paths.extend(
            writes
                .iter()
                .map(|(path, _)| path.clone())
                .chain(std::iter::once(index_path.clone())),
        );
        return match commit_task_import(root, area, &paths) {
            Ok((revision, change_id)) => Ok(CommandOutput::new(
                format!(
                    "Added and committed {} tasks to {area} ({revision})",
                    ids.len()
                ),
                json!({"schema_version": SCHEMA_VERSION, "status": "committed", "area": area, "tasks": ids, "ready": ready, "commit": revision, "change_id": change_id, "paths": relative_paths(root, &paths)?}),
            )),
            Err(error) => Err(import_rollback_error(
                rollback_task_import_index(root, &paths, error),
                &created,
                Some((index_path.as_path(), previous_index.as_slice())),
            )),
        };
    }
    Ok(CommandOutput::new(
        format!("Added {} tasks to {area}", ids.len()),
        json!({"schema_version": SCHEMA_VERSION, "status": "created", "area": area, "tasks": ids, "ready": ready}),
    ))
}

fn import_rollback_error(
    error: ZdevError,
    created: &[PathBuf],
    restore_index: Option<(&Path, &[u8])>,
) -> ZdevError {
    let mut cleanup_errors = created
        .iter()
        .filter_map(|path| {
            fs::remove_file(path)
                .err()
                .map(|cleanup| format!("cannot remove {}: {cleanup}", path.display()))
        })
        .collect::<Vec<_>>();
    if let Some((path, contents)) = restore_index
        && let Err(restore) = write_atomic(path, contents)
    {
        cleanup_errors.push(format!("cannot restore {}: {restore}", path.display()));
    }
    if cleanup_errors.is_empty() {
        ZdevError::new(format!(
            "Could not add tasks; the import was rolled back and no imported task changes were kept. {error}"
        ))
    } else {
        ZdevError::new(format!(
            "Could not add tasks, and cleanup was incomplete. {error}. Resolve these paths before retrying: {}",
            cleanup_errors.join("; "),
        ))
    }
}

fn require_committable_task_import(root: &Path, area: &str) -> Result<Option<PathBuf>, ZdevError> {
    if let Some(operation) = git_operation(root)? {
        return Err(ZdevError::new(format!(
            "Cannot add and commit tasks while a {operation} is in progress. Finish or abort it, then retry"
        )));
    }
    git_output(root, &["rev-parse", "--verify", "HEAD"]).map_err(|_| {
        ZdevError::new(
            "Cannot add and commit tasks before the repository has a commit. Create the initial commit, then retry",
        )
    })?;
    let area_path = format!(".zdev/{area}");
    let brief_relative = format!("{area_path}/brief.md");
    let unstaged = git_output(root, &["diff", "--name-only", "--", &area_path])?;
    let staged = git_output(root, &["diff", "--cached", "--name-only", "--", &area_path])?;
    let untracked = git_output(
        root,
        &[
            "ls-files",
            "--others",
            "--exclude-standard",
            "--",
            &area_path,
        ],
    )?;
    let ignored = git_output(
        root,
        &[
            "ls-files",
            "--others",
            "--ignored",
            "--exclude-standard",
            "--",
            &area_path,
        ],
    )?;
    let brief_changed = unstaged == brief_relative;
    if !staged.is_empty()
        || !untracked.is_empty()
        || !ignored.is_empty()
        || (!unstaged.is_empty() && !brief_changed)
    {
        return Err(ZdevError::new(format!(
            "Cannot add and commit tasks: {area_path} already has local changes. Commit or resolve them first"
        )));
    }
    if !brief_changed {
        return Ok(None);
    }
    let brief = root.join(&brief_relative);
    let metadata = fs::symlink_metadata(&brief)
        .map_err(|error| ZdevError::io(format!("Cannot inspect {}", brief.display()), error))?;
    if !metadata.file_type().is_file() {
        return Err(ZdevError::new(format!(
            "Cannot add and commit tasks: {} must be a tracked regular file",
            brief.display()
        )));
    }
    git_output(
        root,
        &["ls-files", "--error-unmatch", "--", &brief_relative],
    )
    .map_err(|_| {
        ZdevError::new(format!(
            "Cannot add and commit tasks: {} must already be tracked",
            brief.display()
        ))
    })?;
    validate_brief(&brief)?;
    Ok(Some(brief))
}

fn relative_paths(root: &Path, paths: &[PathBuf]) -> Result<Vec<String>, ZdevError> {
    paths
        .iter()
        .map(|path| {
            path.strip_prefix(root)
                .map(|path| path.to_string_lossy().replace('\\', "/"))
                .map_err(|_| {
                    ZdevError::new(format!("Path is outside repository: {}", path.display()))
                })
        })
        .collect()
}

fn commit_task_import(
    root: &Path,
    area: &str,
    paths: &[PathBuf],
) -> Result<(String, String), ZdevError> {
    let relative = relative_paths(root, paths)?;
    let mut add = ProcessCommand::new("git");
    add.args(["add", "-f", "--"]);
    add.args(&relative);
    let output = add
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
        .map_err(|error| ZdevError::io("Cannot stage imported task paths", error))?;
    if !output.status.success() {
        return Err(ZdevError::new(format!(
            "Could not stage the new task files. Resolve the Git error, then retry: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }

    let change_id = generate_change_id()?;
    let mut command = ProcessCommand::new("git");
    command
        .args(["commit", "--only", "-m"])
        .arg(format!("Add tasks to {area}"))
        .args(["-m", &format!("{CHANGE_ID_TRAILER}: {change_id}"), "--"])
        .args(&relative);
    let output = command
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
        .map_err(|error| ZdevError::io("Cannot commit imported task paths", error))?;
    if !output.status.success() {
        return Err(ZdevError::new(format!(
            "Could not commit the new task files. Resolve the Git error, then retry: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    Ok((git_output(root, &["rev-parse", "HEAD"])?, change_id))
}

fn rollback_task_import_index(root: &Path, paths: &[PathBuf], error: ZdevError) -> ZdevError {
    let relative = match relative_paths(root, paths) {
        Ok(relative) => relative,
        Err(rollback) => {
            return ZdevError::new(format!(
                "{error}; cannot identify staged task paths during rollback: {rollback}"
            ));
        }
    };
    let mut reset = ProcessCommand::new("git");
    reset.args(["reset", "-q", "HEAD", "--"]).args(&relative);
    match reset
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .output()
    {
        Ok(output) if output.status.success() => error,
        Ok(output) => ZdevError::new(format!(
            "{error}; cannot unstage imported task paths during rollback: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )),
        Err(rollback) => ZdevError::new(format!(
            "{error}; cannot run Git to unstage imported task paths during rollback: {rollback}"
        )),
    }
}

fn render_draft(header: &TaskHeader, draft: &TaskDraft) -> Result<String, ZdevError> {
    let context = draft
        .context
        .as_deref()
        .map_or_else(String::new, |context| {
            format!("\n\n## Context\n\n{}", context.trim())
        });
    let boundaries = if draft.boundaries.is_empty() {
        String::new()
    } else {
        format!(
            "\n\n## Boundaries\n\n{}",
            draft
                .boundaries
                .iter()
                .map(|item| format!("- {item}"))
                .collect::<Vec<_>>()
                .join("\n")
        )
    };
    let validation = if draft.validation.is_empty() {
        "- Let the verifier choose the smallest useful checks.".to_owned()
    } else {
        draft
            .validation
            .iter()
            .map(|item| format!("- {item}"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    Ok(format!(
        "+++\n{}+++\n# {}\n\n## Outcome\n\n{}{}{}\n\n## Done when\n\n{}\n\n## Validation\n\n{}\n",
        toml::to_string(header)
            .map_err(|error| ZdevError::new(format!("Cannot render task: {error}")))?,
        draft.title,
        draft.outcome,
        context,
        boundaries,
        draft
            .done_when
            .iter()
            .map(|item| format!("- [ ] {item}"))
            .collect::<Vec<_>>()
            .join("\n"),
        validation,
    ))
}

fn load_tasks(root: &Path, area: &str) -> Result<Vec<Task>, ZdevError> {
    let (_, area_dir) = load_area(root, area)?;
    let tasks_dir = area_dir.join("tasks");
    if !tasks_dir.is_dir() {
        return Err(ZdevError::new(format!(
            "Area {area} has no tasks directory: {}",
            tasks_dir.display()
        )));
    }
    let mut tasks = Vec::new();
    for entry in fs::read_dir(&tasks_dir)
        .map_err(|error| ZdevError::io(format!("Cannot list {}", tasks_dir.display()), error))?
    {
        let entry = entry.map_err(|error| ZdevError::io("Cannot inspect task", error))?;
        let path = entry.path();
        if path.extension() != Some(OsStr::new("md")) {
            continue;
        }
        let content = fs::read_to_string(&path)
            .map_err(|error| ZdevError::io(format!("Cannot read {}", path.display()), error))?;
        tasks.push(parse_task(&content, &path, area)?);
    }
    validate_task_slices(root, area, &tasks)?;
    tasks.sort_by(compare_tasks_by_id);
    validate_graph(&tasks)?;
    Ok(tasks)
}

fn parse_task(content: &str, path: &Path, area: &str) -> Result<Task, ZdevError> {
    let rest = content.strip_prefix("+++\n").ok_or_else(|| {
        ZdevError::new(format!("Task lacks TOML frontmatter: {}", path.display()))
    })?;
    let (frontmatter, body) = rest.split_once("+++\n").ok_or_else(|| {
        ZdevError::new(format!("Task has unclosed frontmatter: {}", path.display()))
    })?;
    let header: TaskHeader = toml::from_str(frontmatter)
        .map_err(|error| ZdevError::new(format!("Invalid task {}: {error}", path.display())))?;
    if header.schema_version != SCHEMA_VERSION || header.area != area {
        return Err(ZdevError::new(format!(
            "Task has invalid area or schema: {}",
            path.display()
        )));
    }
    validate_segment(&header.key, "Task key")?;
    if let Some(slice) = &header.slice {
        validate_segment(slice, "Slice key")?;
    }
    let expected_prefix = format!("{area}-");
    if !header.id.starts_with(&expected_prefix) || parse_number(&header.id).is_err() {
        return Err(ZdevError::new(format!("Invalid task ID: {}", header.id)));
    }
    let title = body
        .lines()
        .find_map(|line| line.strip_prefix("# "))
        .filter(|title| !title.trim().is_empty())
        .ok_or_else(|| ZdevError::new(format!("Task lacks a title: {}", path.display())))?
        .to_owned();
    validate_task_body(body, header.status, path)?;
    Ok(Task {
        header,
        title,
        body: body.to_owned(),
        path: path.to_path_buf(),
    })
}

fn validate_task_slices(root: &Path, area: &str, tasks: &[Task]) -> Result<(), ZdevError> {
    let slices = slice_briefs(root, area)?;
    let keys = slices
        .iter()
        .map(|slice| slice.key.as_str())
        .collect::<BTreeSet<_>>();
    for task in tasks {
        if let Some(slice) = &task.header.slice
            && !keys.contains(slice.as_str())
        {
            return Err(ZdevError::new(format!(
                "Task {} references unknown slice {slice}: {}",
                task.header.id,
                task.path.display()
            )));
        }
    }
    Ok(())
}

fn markdown_section<'a>(
    body: &'a str,
    heading: &str,
    path: &Path,
) -> Result<Option<&'a str>, ZdevError> {
    let marker = format!("\n## {heading}\n");
    let matches = body.match_indices(&marker).collect::<Vec<_>>();
    let start = match matches.as_slice() {
        [] => return Ok(None),
        [(start, _)] => start + marker.len(),
        _ => {
            return Err(ZdevError::new(format!(
                "Task repeats ## {heading}: {}",
                path.display()
            )));
        }
    };
    let end = body[start..]
        .find("\n## ")
        .map_or(body.len(), |offset| start + offset);
    Ok(Some(body[start..end].trim()))
}

fn required_markdown_section<'a>(
    body: &'a str,
    heading: &str,
    path: &Path,
) -> Result<&'a str, ZdevError> {
    markdown_section(body, heading, path)?
        .ok_or_else(|| ZdevError::new(format!("Task lacks ## {heading}: {}", path.display())))
}

fn validate_bullet_section(section: &str, heading: &str, path: &Path) -> Result<(), ZdevError> {
    if section.is_empty()
        || section.lines().any(|line| {
            !line.trim().is_empty()
                && line
                    .strip_prefix("- ")
                    .is_none_or(|item| item.trim().is_empty())
        })
    {
        return Err(ZdevError::new(format!(
            "Task ## {heading} must contain a non-empty bullet list: {}",
            path.display()
        )));
    }
    Ok(())
}

fn validate_task_body(body: &str, status: TaskStatus, path: &Path) -> Result<(), ZdevError> {
    let outcome = required_markdown_section(body, "Outcome", path)?;
    if outcome.is_empty() {
        return Err(ZdevError::new(format!(
            "Task ## Outcome is empty: {}",
            path.display()
        )));
    }
    if let Some(boundaries) = markdown_section(body, "Boundaries", path)? {
        validate_bullet_section(boundaries, "Boundaries", path)?;
    }
    let done_when = required_markdown_section(body, "Done when", path)?;
    let conditions = done_when
        .lines()
        .filter(|line| !line.trim().is_empty())
        .collect::<Vec<_>>();
    if conditions.is_empty()
        || conditions.iter().any(|line| {
            ["- [ ] ", "- [x] ", "- [X] "]
                .iter()
                .find_map(|prefix| line.strip_prefix(prefix))
                .is_none_or(|item| item.trim().is_empty())
        })
    {
        return Err(ZdevError::new(format!(
            "Task ## Done when must contain only checklist items: {}",
            path.display()
        )));
    }
    if status == TaskStatus::Done && conditions.iter().any(|line| line.starts_with("- [ ] ")) {
        return Err(ZdevError::new(format!(
            "Done task has unchecked conditions: {}",
            path.display()
        )));
    }
    let validation = required_markdown_section(body, "Validation", path)?;
    validate_bullet_section(validation, "Validation", path)?;
    if status == TaskStatus::Done {
        let result = required_markdown_section(body, "Result", path)?;
        if result.is_empty() {
            return Err(ZdevError::new(format!(
                "Done task has an empty ## Result: {}",
                path.display()
            )));
        }
    }
    Ok(())
}

fn replace_markdown_section(
    body: &str,
    heading: &str,
    path: &Path,
    replace: impl FnOnce(&str) -> String,
) -> Result<String, ZdevError> {
    let marker = format!("\n## {heading}\n");
    let start = body
        .find(&marker)
        .ok_or_else(|| ZdevError::new(format!("Task lacks ## {heading}: {}", path.display())))?
        + marker.len();
    let end = body[start..]
        .find("\n## ")
        .map_or(body.len(), |offset| start + offset);
    let mut updated = String::with_capacity(body.len());
    updated.push_str(&body[..start]);
    updated.push_str(&replace(&body[start..end]));
    updated.push_str(&body[end..]);
    Ok(updated)
}

fn parse_number(id: &str) -> Result<u64, ZdevError> {
    id.rsplit_once('-')
        .and_then(|(_, number)| number.parse().ok())
        .ok_or_else(|| ZdevError::new(format!("Task ID has no numeric suffix: {id}")))
}

fn compare_tasks_by_id(left: &Task, right: &Task) -> std::cmp::Ordering {
    parse_number(&left.header.id)
        .expect("task IDs are validated before sorting")
        .cmp(&parse_number(&right.header.id).expect("task IDs are validated before sorting"))
        .then_with(|| left.header.id.cmp(&right.header.id))
}

fn validate_graph(tasks: &[Task]) -> Result<(), ZdevError> {
    let by_id = tasks
        .iter()
        .map(|task| (task.header.id.as_str(), task))
        .collect::<BTreeMap<_, _>>();
    if by_id.len() != tasks.len() {
        return Err(ZdevError::new("Task IDs must be unique"));
    }
    let keys = tasks
        .iter()
        .map(|task| task.header.key.as_str())
        .collect::<BTreeSet<_>>();
    if keys.len() != tasks.len() {
        return Err(ZdevError::new("Task keys must be unique"));
    }
    for task in tasks {
        let mut seen = BTreeSet::new();
        for blocker in &task.header.blocked_by {
            if blocker == &task.header.id || !seen.insert(blocker) {
                return Err(ZdevError::new(format!(
                    "Invalid blocker on {}",
                    task.header.id
                )));
            }
            if !by_id.contains_key(blocker.as_str()) {
                return Err(ZdevError::new(format!(
                    "Task {} has missing blocker {blocker}",
                    task.header.id
                )));
            }
        }
    }
    fn visit<'a>(
        id: &'a str,
        by_id: &BTreeMap<&'a str, &'a Task>,
        visiting: &mut BTreeSet<&'a str>,
        visited: &mut BTreeSet<&'a str>,
    ) -> Result<(), ZdevError> {
        if visited.contains(id) {
            return Ok(());
        }
        if !visiting.insert(id) {
            return Err(ZdevError::new(format!(
                "Task dependency cycle includes {id}"
            )));
        }
        for blocker in &by_id[id].header.blocked_by {
            visit(blocker, by_id, visiting, visited)?;
        }
        visiting.remove(id);
        visited.insert(id);
        Ok(())
    }
    let mut visiting = BTreeSet::new();
    let mut visited = BTreeSet::new();
    for id in by_id.keys().copied() {
        visit(id, &by_id, &mut visiting, &mut visited)?;
    }
    Ok(())
}

fn task_state(task: &Task, tasks: &[Task]) -> &'static str {
    if task.header.status == TaskStatus::Done {
        return "done";
    }
    let statuses = tasks
        .iter()
        .map(|task| (task.header.id.as_str(), task.header.status))
        .collect::<BTreeMap<_, _>>();
    if task
        .header
        .blocked_by
        .iter()
        .all(|id| statuses.get(id.as_str()) == Some(&TaskStatus::Done))
    {
        "ready"
    } else {
        "blocked"
    }
}

fn views<'a>(root: &Path, tasks: &'a [Task]) -> Vec<TaskView<'a>> {
    tasks
        .iter()
        .map(|task| TaskView {
            id: &task.header.id,
            title: &task.title,
            status: task.header.status.as_str(),
            state: task_state(task, tasks),
            complexity: task.complexity(),
            blocked_by: &task.header.blocked_by,
            slice: task.header.slice.as_deref(),
            slice_brief: task_slice_brief_path(root, task),
            path: relative(root, &task.path),
        })
        .collect()
}

pub(super) fn list(root: &Path, area: &str) -> Result<CommandOutput, ZdevError> {
    let tasks = load_tasks(root, area)?;
    let task_views = views(root, &tasks);
    let text = if task_views.is_empty() {
        format!("No tasks in {area}")
    } else {
        task_views
            .iter()
            .map(|task| {
                let slice = task
                    .slice
                    .map(|slice| format!("  slice:{slice}"))
                    .unwrap_or_default();
                format!(
                    "{}  {:7}  {}  complexity:{}{slice}",
                    task.id,
                    task.state,
                    task.title,
                    task.complexity.as_str()
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    };
    Ok(CommandOutput::new(
        text,
        json!({"schema_version": SCHEMA_VERSION, "area": area, "tasks": task_views}),
    ))
}

fn next_task(tasks: &[Task]) -> Option<&Task> {
    tasks.iter().find(|task| task_state(task, tasks) == "ready")
}

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "lowercase")]
pub(super) enum QueueState {
    Empty,
    Ready,
    Blocked,
    Exhausted,
}

impl QueueState {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Empty => "empty",
            Self::Ready => "ready",
            Self::Blocked => "blocked",
            Self::Exhausted => "exhausted",
        }
    }
}

fn select_area(root: &Path, requested: Option<&str>) -> Result<String, ZdevError> {
    if let Some(area) = requested {
        load_area(root, area)?;
        return Ok(area.to_owned());
    }
    let config = read_config(root)?;
    if let Some(area) = config.project.default_area {
        load_area(root, &area)?;
        return Ok(area);
    }
    let mut active = Vec::new();
    for area in list_areas(root)? {
        if area.lifecycle == AreaLifecycle::Open {
            active.push(area.tag);
        }
    }
    match active.as_slice() {
        [only] => Ok(only.clone()),
        [] => Err(ZdevError::new(
            "No area is open. Run `zdev area reopen <area>` before selecting work",
        )),
        _ => Err(ZdevError::new(format!(
            "Specify an area with `zdev next <area>`. Open areas: {}",
            active.join(", ")
        ))),
    }
}

pub(super) fn next(root: &Path, requested: Option<&str>) -> Result<CommandOutput, ZdevError> {
    let area = select_area(root, requested)?;
    let metadata = load_area(root, &area)?.0;
    if metadata.lifecycle == AreaLifecycle::Closed {
        validate_brief(&root.join(".zdev").join(&area).join("brief.md"))?;
        super::project::validate_area_relationships(&list_areas(root)?)?;
        super::project::validate_slices(root, &area)?;
        validate_index(root, &area)?;
        let summary = summary(root, &area)?;
        validate_area_lifecycle(&metadata, &summary)?;
        let queue = summary.queue().as_str();
        return Ok(CommandOutput::new(
            format!(
                "Area {area} is closed. Run `zdev area reopen {area}` before adding or selecting work"
            ),
            json!({"schema_version": SCHEMA_VERSION, "area": area, "lifecycle": "closed", "queue": queue, "task": Value::Null}),
        ));
    }
    let branch = require_task_work_area_link(root, &area)?;
    let tasks = load_tasks(root, &area)?;
    let Some(task) = next_task(&tasks) else {
        let summary = summary(root, &area)?;
        validate_area_lifecycle(&metadata, &summary)?;
        let queue = summary.queue().as_str();
        let mut text = if queue == "empty" {
            format!(
                "No tasks are recorded in open area {area}. Add approved tasks or run `zdev area close {area}`"
            )
        } else if queue == "exhausted" {
            format!(
                "The task queue is exhausted in open area {area}. Add approved tasks, reopen a task, or run `zdev area close {area}`"
            )
        } else {
            return Err(ZdevError::new(
                "Validated task graph has open work but no ready task",
            ));
        };
        if let Some(advisory) = &branch.advisory {
            text.push('\n');
            text.push_str(advisory);
        }
        return Ok(CommandOutput::new(
            text,
            json!({"schema_version": SCHEMA_VERSION, "area": area, "lifecycle": "open", "queue": queue, "task": Value::Null, "branch_status": branch.branch_status, "advisory": branch.advisory}),
        ));
    };
    let view = TaskView {
        id: &task.header.id,
        title: &task.title,
        status: task.header.status.as_str(),
        state: "ready",
        complexity: task.complexity(),
        blocked_by: &task.header.blocked_by,
        slice: task.header.slice.as_deref(),
        slice_brief: task_slice_brief_path(root, task),
        path: relative(root, &task.path),
    };
    let mut text = format!(
        "Area: {area}\nLifecycle: open\nQueue: ready\n\n{}  {}\nComplexity: {}\n{}",
        task.header.id,
        task.title,
        task.complexity().as_str(),
        task.path.display()
    );
    if let (Some(slice), Some(path)) = (&task.header.slice, &view.slice_brief) {
        text.push_str(&format!("\nSlice: {slice}\nSlice brief: {path}"));
    }
    if let Some(advisory) = &branch.advisory {
        text.push('\n');
        text.push_str(advisory);
    }
    Ok(CommandOutput::new(
        text,
        json!({"schema_version": SCHEMA_VERSION, "area": area, "lifecycle": "open", "queue": "ready", "task": view, "branch_status": branch.branch_status, "advisory": branch.advisory}),
    ))
}

pub(super) fn next_any(root: &Path) -> Result<CommandOutput, ZdevError> {
    let config = read_config(root)?;
    let areas = list_areas(root)?;
    let by_tag = areas
        .iter()
        .map(|area| (area.tag.as_str(), area))
        .collect::<BTreeMap<_, _>>();
    let mut candidates = Vec::new();
    let mut skipped = Vec::new();
    let mut unsafe_open_work = false;
    let closed_areas = areas
        .iter()
        .filter(|area| area.lifecycle == AreaLifecycle::Closed)
        .map(|area| area.tag.clone())
        .collect::<Vec<_>>();
    let checked_out = if closed_areas.len() == areas.len() {
        None
    } else {
        current_branch(root)?
    };

    for area in &areas {
        if area.lifecycle == AreaLifecycle::Closed {
            let summary = summary(root, &area.tag)?;
            validate_area_lifecycle(area, &summary)?;
            continue;
        }
        let tasks = load_tasks(root, &area.tag)?;
        let branch_status =
            area_branch_status(root, &config, area, &by_tag, checked_out.as_deref());
        let structurally_safe = branch_status["task_work"]["structurally_safe"]
            .as_bool()
            .unwrap_or(false);
        let open = tasks
            .iter()
            .any(|task| task.header.status == TaskStatus::Open);

        if !structurally_safe {
            unsafe_open_work |= open;
            skipped.push(json!({
                "area": area.tag,
                "branch": area.branch,
                "branch_matches": branch_status["branch_matches"],
                "diagnostics": branch_status["diagnostics"],
                "branch_status": branch_status,
            }));
            continue;
        }

        if let Some(task) = next_task(&tasks) {
            candidates.push((area, task.clone(), branch_status));
        }
    }

    candidates.sort_by(|left, right| {
        let left_matches = left.2["branch_matches"] == Value::Bool(true);
        let right_matches = right.2["branch_matches"] == Value::Bool(true);
        right_matches
            .cmp(&left_matches)
            .then_with(|| left.0.tag.cmp(&right.0.tag))
    });

    let Some((area, task, branch_status)) = candidates.into_iter().next() else {
        let selection = if unsafe_open_work { "unsafe" } else { "none" };
        let mut text = match selection {
            "unsafe" => format!(
                "No safe task is ready. Unsafe areas: {}",
                skipped_areas_text(&skipped)
            ),
            _ if closed_areas.len() == areas.len() => {
                "No area is open. Run `zdev area reopen <area>` before selecting work".to_owned()
            }
            _ => "No open area has ready work. Open task queues are empty or exhausted".to_owned(),
        };
        append_closed_areas(&mut text, &closed_areas);
        let reason = if selection == "none" {
            Some(if closed_areas.len() == areas.len() {
                "no-open-area"
            } else {
                "no-ready-open-area"
            })
        } else {
            None
        };
        let value = if let Some(reason) = reason {
            json!({
                "schema_version": SCHEMA_VERSION,
                "mode": "any",
                "selection": selection,
                "reason": reason,
                "task": Value::Null,
                "skipped": skipped,
                "closed_areas": closed_areas,
            })
        } else {
            json!({
                "schema_version": SCHEMA_VERSION,
                "mode": "any",
                "selection": selection,
                "task": Value::Null,
                "skipped": skipped,
                "closed_areas": closed_areas,
            })
        };
        return Ok(CommandOutput::new(text, value));
    };

    let branch_matches = branch_status["branch_matches"] == Value::Bool(true);
    let branch_note = if branch_matches {
        " (checked out)".to_owned()
    } else if let Some(checked_out) = &checked_out {
        format!(" (not checked out; current branch: {checked_out})")
    } else {
        " (not checked out; HEAD is detached)".to_owned()
    };
    let view = TaskView {
        id: &task.header.id,
        title: &task.title,
        status: task.header.status.as_str(),
        state: "ready",
        complexity: task.complexity(),
        blocked_by: &task.header.blocked_by,
        slice: task.header.slice.as_deref(),
        slice_brief: task_slice_brief_path(root, &task),
        path: relative(root, &task.path),
    };
    let mut text = format!(
        "Selection: ready\n\n{}  {}\nComplexity: {}\nArea: {}\nRequired branch: {}{}\nTask: {}",
        task.header.id,
        task.title,
        task.complexity().as_str(),
        area.tag,
        area.branch,
        branch_note,
        view.path
    );
    if let (Some(slice), Some(path)) = (&task.header.slice, &view.slice_brief) {
        text.push_str(&format!("\nSlice: {slice}\nSlice brief: {path}"));
    }
    if !skipped.is_empty() {
        text.push_str(&format!(
            "\nSkipped unsafe areas: {}",
            skipped_areas_text(&skipped)
        ));
    }
    append_closed_areas(&mut text, &closed_areas);
    Ok(CommandOutput::new(
        text,
        json!({
            "schema_version": SCHEMA_VERSION,
            "mode": "any",
            "selection": "ready",
            "area": area.tag,
            "lifecycle": "open",
            "queue": "ready",
            "branch": area.branch,
            "branch_matches": branch_matches,
            "task": view,
            "branch_status": branch_status,
            "skipped": skipped,
            "closed_areas": closed_areas,
        }),
    ))
}

fn append_closed_areas(text: &mut String, closed_areas: &[String]) {
    if !closed_areas.is_empty() {
        text.push_str("\nExcluded closed areas: ");
        text.push_str(&closed_areas.join(", "));
    }
}

fn skipped_areas_text(skipped: &[Value]) -> String {
    skipped
        .iter()
        .map(|area| {
            let tag = area["area"].as_str().unwrap_or("unknown");
            let diagnostics = area["diagnostics"]
                .as_array()
                .map(|items| {
                    items
                        .iter()
                        .filter_map(Value::as_str)
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .unwrap_or_default();
            format!("{tag} [{diagnostics}]")
        })
        .collect::<Vec<_>>()
        .join("; ")
}

pub(super) fn show(root: &Path, area: &str, id: &str) -> Result<CommandOutput, ZdevError> {
    let tasks = load_tasks(root, area)?;
    let task = find_task(&tasks, id)?;
    let content = fs::read_to_string(&task.path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", task.path.display()), error))?;
    let slice_brief = task_slice_brief_path(root, task);
    let text = match (&task.header.slice, &slice_brief) {
        (Some(slice), Some(path)) => format!(
            "Complexity: {}\nSlice: {slice}\nSlice brief: {path}\n\n{content}",
            task.complexity().as_str()
        ),
        _ => format!("Complexity: {}\n\n{content}", task.complexity().as_str()),
    };
    Ok(CommandOutput::new(
        text,
        json!({
            "schema_version": SCHEMA_VERSION,
            "area": area,
            "id": task.header.id,
            "title": task.title,
            "status": task.header.status.as_str(),
            "state": task_state(task, &tasks),
            "complexity": task.complexity(),
            "blocked_by": task.header.blocked_by,
            "slice": task.header.slice,
            "slice_brief": slice_brief,
            "path": relative(root, &task.path),
            "body": task.body,
        }),
    ))
}

fn task_slice_brief_path(root: &Path, task: &Task) -> Option<String> {
    task.header.slice.as_deref().map(|slice| {
        relative(
            root,
            &root
                .join(".zdev")
                .join(&task.header.area)
                .join("slices")
                .join(format!("{slice}.md")),
        )
    })
}

fn find_task<'a>(tasks: &'a [Task], id: &str) -> Result<&'a Task, ZdevError> {
    tasks
        .iter()
        .find(|task| task.header.id == id)
        .ok_or_else(|| ZdevError::new(format!("Unknown task: {id}")))
}

pub(super) fn complete(
    root: &Path,
    area: &str,
    id: &str,
    summary: &str,
    validation: &[String],
) -> Result<CommandOutput, ZdevError> {
    let branch = require_task_work_area_link(root, area)?;
    validate_nonempty_line(summary, "Completion summary")?;
    for item in validation {
        validate_nonempty_line(item, "Validation result")?;
    }
    let _lock = ZdevStateLock::acquire(root)?;
    let tasks = load_tasks(root, area)?;
    let task = find_task(&tasks, id)?;
    if task.header.status == TaskStatus::Done {
        return Ok(CommandOutput::new(
            format!("Task {id} is already done"),
            json!({"schema_version": SCHEMA_VERSION, "status": "unchanged", "area": area, "task": id}),
        ));
    }
    if task_state(task, &tasks) != "ready" {
        return Err(ZdevError::new(format!(
            "Cannot complete task {id}: it is blocked. Complete its blockers first"
        )));
    }
    let mut header = task.header.clone();
    header.status = TaskStatus::Done;
    let mut body = replace_markdown_section(&task.body, "Done when", &task.path, |section| {
        section.replace("- [ ] ", "- [x] ")
    })?;
    if !body.ends_with('\n') {
        body.push('\n');
    }
    body.push_str("\n## Result\n\n");
    body.push_str(summary);
    body.push_str("\n\nValidation:\n\n");
    for item in validation {
        body.push_str(&format!("- {item}\n"));
    }
    let content = format!("+++\n{}+++\n{}", toml::to_string(&header).unwrap(), body);
    publish_task_and_index(root, area, task, &content)?;
    let mut text = format!("Completed task {id}");
    if let Some(advisory) = &branch.advisory {
        text.push('\n');
        text.push_str(advisory);
    }
    Ok(CommandOutput::new(
        text,
        json!({"schema_version": SCHEMA_VERSION, "status": "done", "area": area, "task": id, "branch_status": branch.branch_status, "advisory": branch.advisory}),
    ))
}

pub(super) fn reopen(root: &Path, area: &str, id: &str) -> Result<CommandOutput, ZdevError> {
    let _lock = ZdevStateLock::acquire(root)?;
    let metadata = load_area(root, area)?.0;
    if metadata.lifecycle == AreaLifecycle::Closed {
        return Err(ZdevError::new(format!(
            "Cannot reopen task {id} in closed area {area}. Run `zdev area reopen {area}` first"
        )));
    }
    let tasks = load_tasks(root, area)?;
    let task = find_task(&tasks, id)?;
    if task.header.status == TaskStatus::Open {
        return Ok(CommandOutput::new(
            format!("Task {id} is already open"),
            json!({"schema_version": SCHEMA_VERSION, "status": "unchanged", "area": area, "task": id}),
        ));
    }
    if tasks.iter().any(|candidate| {
        candidate.header.status == TaskStatus::Done
            && candidate
                .header
                .blocked_by
                .iter()
                .any(|blocker| blocker == id)
    }) {
        return Err(ZdevError::new(format!(
            "Cannot reopen {id}: a completed task depends on it. Reopen dependent completed tasks first"
        )));
    }
    let mut header = task.header.clone();
    header.status = TaskStatus::Open;
    let body = task
        .body
        .split("\n## Result\n")
        .next()
        .unwrap_or(&task.body);
    let body = replace_markdown_section(body, "Done when", &task.path, |section| {
        section
            .replace("- [x] ", "- [ ] ")
            .replace("- [X] ", "- [ ] ")
    })?;
    let content = format!("+++\n{}+++\n{}", toml::to_string(&header).unwrap(), body);
    publish_task_and_index(root, area, task, &content)?;
    Ok(CommandOutput::new(
        format!("Reopened task {id}"),
        json!({"schema_version": SCHEMA_VERSION, "status": "open", "area": area, "task": id}),
    ))
}

fn publish_task_and_index(
    root: &Path,
    area: &str,
    current: &Task,
    content: &str,
) -> Result<(), ZdevError> {
    let index_path = root.join(".zdev").join(area).join("TASKS.md");
    let original_task = fs::read(&current.path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", current.path.display()), error))?;
    let original_index = fs::read(&index_path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", index_path.display()), error))?;
    let mut tasks = load_tasks(root, area)?;
    let updated = parse_task(content, &current.path, area)?;
    let slot = tasks
        .iter_mut()
        .find(|task| task.header.id == current.header.id)
        .ok_or_else(|| ZdevError::new(format!("Unknown task: {}", current.header.id)))?;
    *slot = updated;
    let index = render_index(area, &tasks)?;

    write_atomic(&current.path, content.as_bytes())?;
    if let Err(error) = write_atomic(&index_path, index.as_bytes()) {
        let task_rollback = write_atomic(&current.path, &original_task);
        let index_rollback = write_atomic(&index_path, &original_index);
        if let Err(rollback) = task_rollback.and(index_rollback) {
            return Err(ZdevError::new(format!(
                "{error}; rollback also failed: {rollback}"
            )));
        }
        return Err(error);
    }
    Ok(())
}

fn render_index(area: &str, tasks: &[Task]) -> Result<String, ZdevError> {
    validate_graph(tasks)?;
    let ready = tasks
        .iter()
        .filter(|task| task_state(task, tasks) == "ready")
        .count();
    let blocked = tasks
        .iter()
        .filter(|task| task_state(task, tasks) == "blocked")
        .count();
    let done = tasks
        .iter()
        .filter(|task| task.header.status == TaskStatus::Done)
        .count();
    let has_slices = tasks.iter().any(|task| task.header.slice.is_some());
    let columns = if has_slices {
        "| ID | Task | Slice | State | Blocked by |\n| --- | --- | --- | --- | --- |\n"
    } else {
        "| ID | Task | State | Blocked by |\n| --- | --- | --- | --- |\n"
    };
    let mut result = format!(
        "{GENERATED_MARKER}\n\n# Tasks: {area}\n\n- Total: {}\n- Ready: {ready}\n- Blocked: {blocked}\n- Done: {done}\n\n{columns}",
        tasks.len()
    );
    for task in tasks {
        let blockers = if task.header.blocked_by.is_empty() {
            "—".to_owned()
        } else {
            task.header.blocked_by.join(", ")
        };
        let filename = task
            .path
            .file_name()
            .and_then(OsStr::to_str)
            .unwrap_or("task.md");
        if has_slices {
            let slice = task.header.slice.as_deref().unwrap_or("—");
            result.push_str(&format!(
                "| [{}](tasks/{filename}) | {} | {slice} | {} | {blockers} |\n",
                task.header.id,
                table_text(&task.title),
                task_state(task, tasks),
            ));
        } else {
            result.push_str(&format!(
                "| [{}](tasks/{filename}) | {} | {} | {blockers} |\n",
                task.header.id,
                table_text(&task.title),
                task_state(task, tasks),
            ));
        }
    }
    Ok(result)
}

pub(super) fn empty_index(area: &str) -> Result<String, ZdevError> {
    render_index(area, &[])
}

pub(super) struct GoalTaskRead {
    pub id: String,
    pub key: String,
    pub title: String,
    pub complexity: TaskComplexity,
    pub path: PathBuf,
    pub outcome: String,
    pub context: Option<String>,
    pub boundaries: Option<String>,
    pub done_when: String,
    pub validation: String,
    pub blocked_by: Vec<String>,
    pub slice: Option<String>,
}

pub(super) struct GoalTasksRead {
    pub total: usize,
    pub open: usize,
    pub ready: usize,
    pub blocked: usize,
    pub done: usize,
    pub focus: Option<GoalTaskRead>,
}

pub(super) fn goal_tasks(root: &Path, area: &str) -> Result<GoalTasksRead, ZdevError> {
    let tasks = load_tasks(root, area)?;
    let ready = tasks
        .iter()
        .filter(|task| task_state(task, &tasks) == "ready")
        .count();
    let blocked = tasks
        .iter()
        .filter(|task| task_state(task, &tasks) == "blocked")
        .count();
    let done = tasks
        .iter()
        .filter(|task| task.header.status == TaskStatus::Done)
        .count();
    let focus = next_task(&tasks)
        .map(|task| {
            Ok(GoalTaskRead {
                id: task.header.id.clone(),
                key: task.header.key.clone(),
                title: task.title.clone(),
                complexity: task.complexity(),
                path: task.path.clone(),
                outcome: required_markdown_section(&task.body, "Outcome", &task.path)?.to_owned(),
                context: markdown_section(&task.body, "Context", &task.path)?.map(str::to_owned),
                boundaries: markdown_section(&task.body, "Boundaries", &task.path)?
                    .map(str::to_owned),
                done_when: required_markdown_section(&task.body, "Done when", &task.path)?
                    .to_owned(),
                validation: required_markdown_section(&task.body, "Validation", &task.path)?
                    .to_owned(),
                blocked_by: task.header.blocked_by.clone(),
                slice: task.header.slice.clone(),
            })
        })
        .transpose()?;
    Ok(GoalTasksRead {
        total: tasks.len(),
        open: tasks.len() - done,
        ready,
        blocked,
        done,
        focus,
    })
}

fn write_index(root: &Path, area: &str) -> Result<PathBuf, ZdevError> {
    let (_, area_dir) = load_area(root, area)?;
    let tasks = load_tasks(root, area)?;
    let path = area_dir.join("TASKS.md");
    write_atomic(&path, render_index(area, &tasks)?.as_bytes())?;
    Ok(path)
}

pub(super) fn index(root: &Path, area: &str) -> Result<CommandOutput, ZdevError> {
    let _lock = ZdevStateLock::acquire(root)?;
    let path = write_index(root, area)?;
    Ok(CommandOutput::new(
        format!("Updated {}", relative(root, &path)),
        json!({"schema_version": SCHEMA_VERSION, "status": "updated", "area": area, "path": relative(root, &path)}),
    ))
}

pub(super) struct AreaTaskSummary {
    pub total: usize,
    pub ready: usize,
    pub blocked: usize,
    pub done: usize,
    pub open: usize,
    pub next: Option<String>,
    pub next_complexity: Option<TaskComplexity>,
    pub slices: Vec<SliceTaskSummary>,
}

impl AreaTaskSummary {
    pub(super) fn queue(&self) -> QueueState {
        if self.total == 0 {
            QueueState::Empty
        } else if self.ready > 0 {
            QueueState::Ready
        } else if self.open > 0 {
            QueueState::Blocked
        } else {
            QueueState::Exhausted
        }
    }
}

pub(super) fn validate_area_lifecycle(
    area: &AreaMetadata,
    summary: &AreaTaskSummary,
) -> Result<(), ZdevError> {
    if area.lifecycle == AreaLifecycle::Closed && summary.open > 0 {
        return Err(ZdevError::new(format!(
            "Closed area {} has {} open tasks",
            area.tag, summary.open
        )));
    }
    if matches!(summary.queue(), QueueState::Blocked) {
        return Err(ZdevError::new(
            "Validated task graph has open work but no ready task",
        ));
    }
    Ok(())
}

#[derive(Serialize)]
pub(super) struct SliceTaskSummary {
    pub key: String,
    pub title: String,
    pub path: String,
    pub ready: usize,
    pub blocked: usize,
    pub done: usize,
}

pub(super) fn summary(root: &Path, area: &str) -> Result<AreaTaskSummary, ZdevError> {
    let tasks = load_tasks(root, area)?;
    let ready = tasks
        .iter()
        .filter(|task| task_state(task, &tasks) == "ready")
        .count();
    let blocked = tasks
        .iter()
        .filter(|task| task_state(task, &tasks) == "blocked")
        .count();
    let done = tasks
        .iter()
        .filter(|task| task.header.status == TaskStatus::Done)
        .count();
    let slices = slice_briefs(root, area)?
        .into_iter()
        .map(|slice| {
            let slice_tasks = tasks
                .iter()
                .filter(|task| task.header.slice.as_deref() == Some(slice.key.as_str()))
                .collect::<Vec<_>>();
            SliceTaskSummary {
                key: slice.key,
                title: slice.title,
                path: relative(root, &slice.path),
                ready: slice_tasks
                    .iter()
                    .filter(|task| task_state(task, &tasks) == "ready")
                    .count(),
                blocked: slice_tasks
                    .iter()
                    .filter(|task| task_state(task, &tasks) == "blocked")
                    .count(),
                done: slice_tasks
                    .iter()
                    .filter(|task| task.header.status == TaskStatus::Done)
                    .count(),
            }
        })
        .collect();
    Ok(AreaTaskSummary {
        total: tasks.len(),
        ready,
        blocked,
        done,
        open: tasks.len() - done,
        next: next_task(&tasks).map(|task| task.header.id.clone()),
        next_complexity: next_task(&tasks).map(Task::complexity),
        slices,
    })
}

pub(super) fn validate_index(root: &Path, area: &str) -> Result<(), ZdevError> {
    let tasks = load_tasks(root, area)?;
    let expected = render_index(area, &tasks)?;
    let path = root.join(".zdev").join(area).join("TASKS.md");
    let actual = fs::read_to_string(&path)
        .map_err(|error| ZdevError::io(format!("Cannot read {}", path.display()), error))?;
    if actual != expected {
        return Err(ZdevError::new(format!(
            "Generated task summary is stale: {}",
            path.display()
        )));
    }
    Ok(())
}

fn slug(value: &str) -> String {
    let mut slug = String::new();
    let mut separator = false;
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric() {
            if separator && !slug.is_empty() {
                slug.push('-');
            }
            slug.push(char::from(byte.to_ascii_lowercase()));
            separator = false;
        } else if !slug.is_empty() {
            separator = true;
        }
    }
    if slug.is_empty() {
        "task".to_owned()
    } else {
        slug.truncate(60);
        slug.trim_end_matches('-').to_owned()
    }
}

fn table_text(value: &str) -> String {
    value.replace('|', "\\|")
}
